# Generated by Django 5.2.17 on 2026-09-22 17:58

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('locale', models.CharField(default='en', max_length=2)),
                ('mode', models.CharField(default='general', max_length=16)),
                ('time_zone', models.CharField(default='UTC', max_length=64)),
                ('preferences', models.JSONField(default=dict)),
                ('plan', models.CharField(default='free', max_length=12)),
                ('is_test', models.BooleanField(default=False)),
                ('first_verified_channel', models.CharField(default='web', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('verifier_hash', models.CharField(max_length=64)),
                ('browser_hint', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(null=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='BotCallback',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=180, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('page_count', models.PositiveIntegerField()),
                ('state', models.CharField(default='ready', max_length=16)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_id', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('input_ids', models.JSONField(default=list)),
                ('policy', models.JSONField(default=dict)),
                ('meters', models.JSONField(default=dict)),
                ('settled_meters', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='queued', max_length=24)),
                ('origin_channel', models.CharField(default='web', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('lease_expires_at', models.DateTimeField(null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('engine', models.CharField(blank=True, max_length=120)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='user_document', max_length=24)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.fileasset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('feature_id', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(default='web', max_length=16)),
                ('locale', models.CharField(default='en', max_length=2)),
                ('plan_at_event', models.CharField(default='free', max_length=12)),
                ('environment', models.CharField(default='development', max_length=16)),
                ('properties', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_id', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('input_ids', models.JSONField(default=list)),
                ('input_fingerprints', models.JSONField(default=list)),
                ('meters', models.JSONField(default=dict)),
                ('policy', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.quote'),
        ),
        migrations.CreateModel(
            name='BotDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(default='pdf.merge', max_length=100)),
                ('input_ids', models.JSONField(default=list)),
                ('state', models.CharField(default='collecting', max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quote')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('category', models.CharField(default='general', max_length=24)),
                ('status', models.CharField(default='open', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='core.account')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='UsageGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meter', models.CharField(max_length=24)),
                ('source', models.CharField(default='included', max_length=16)),
                ('source_id', models.CharField(max_length=160, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('consumed', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('expires_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_grants', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.CharField(max_length=24)),
                ('amount', models.PositiveIntegerField()),
                ('settled', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.job')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usagegrant')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.CharField(max_length=24)),
                ('kind', models.CharField(max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usagegrant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(default='job.execute', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'topic'), name='outbox_job_topic')],
            },
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('account', 'idempotency_key'), name='job_account_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='usagegrant',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', django.db.models.expressions.CombinedExpression(models.F('consumed'), '+', models.F('reserved')))), name='grant_no_overspend'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('job', 'grant'), name='one_reservation_per_grant'),
        ),
        migrations.AddConstraint(
            model_name='usageledger',
            constraint=models.UniqueConstraint(fields=('job', 'grant', 'kind'), name='one_ledger_transition'),
        ),
    ]
