# Generated by Django 5.2.17 on 2026-09-22 18:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='secret_id',
            field=models.UUIDField(null=True),
        ),
        migrations.CreateModel(
            name='SecretHandle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ciphertext', models.BinaryField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fileasset')),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
        ),
    ]
