# Generated by Django 5.2.17 on 2026-09-22 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quote_secret_id_secrethandle'),
    ]

    operations = [
        migrations.AddField(
            model_name='botdraft',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='botdraft',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BotInputReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fileasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'chat_id', 'message_id'), name='one_bot_input_receipt')],
            },
        ),
    ]
