# Generated by Django 5.2.17 on 2026-09-22 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_botdraft_parameters_botdraft_version_botinputreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_previews', to='core.fileasset')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview_for', to='core.fileasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'page'), name='one_preview_per_page')],
            },
        ),
    ]
