# Generated by Django 5.2.17 on 2026-09-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pagepreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='publish_attempts',
            field=models.PositiveIntegerField(default=0, db_default=0),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='publish_lease_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
