# Generated by Django 5.2.17 on 2026-09-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_outboxevent_publish_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='publish_attempts',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
