# Generated by Django 5.2.17 on 2026-09-23 20:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_outboxevent_publish_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRateLimit',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='auth_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='account',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='password_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='authchallenge',
            name='intent',
            field=models.CharField(default='login', max_length=8),
        ),
        migrations.AddField(
            model_name='authchallenge',
            name='link_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.account'),
        ),
        migrations.AddField(
            model_name='authchallenge',
            name='link_auth_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authchallenge',
            name='telegram_user',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='account',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='EmailChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=16)),
                ('auth_version', models.PositiveIntegerField(default=0)),
                ('password_hash', models.CharField(blank=True, max_length=256)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('locale', models.CharField(default='en', max_length=2)),
                ('eligible', models.BooleanField(default=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('browser_hash', models.CharField(max_length=64)),
                ('nonce', models.CharField(max_length=128)),
                ('verifier', models.CharField(max_length=128)),
                ('intent', models.CharField(max_length=8)),
                ('auth_version', models.PositiveIntegerField(default=0)),
                ('client_id', models.CharField(max_length=255)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('locale', models.CharField(default='en', max_length=2)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
    ]
