# Generated by Django 5.2.17 on 2026-09-23 22:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_botconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotJobNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(null=True)),
                ('message_id', models.BigIntegerField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_notice', to='core.job')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='bot_notice_due')],
            },
        ),
    ]
