# Generated by Django 5.2.17 on 2026-09-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bot_job_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotVerification',
            fields=[
                ('telegram_user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nonce', models.CharField(blank=True, default='', max_length=32)),
                ('challenge', models.JSONField(default=dict)),
                ('pending', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_until', models.DateTimeField(blank=True, null=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('prompt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
