# Generated by Django 5.2.17 on 2026-09-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_botverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='staff_plan',
            field=models.CharField(blank=True, db_default='', max_length=12),
        ),
        migrations.AddField(
            model_name='account',
            name='staff_plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
