# Generated by Django 5.2.17 on 2026-10-03 01:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_triple_ai_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=64)),
                ('is_member', models.BooleanField()),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to='core.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'chat'), name='one_channel_membership')],
            },
        ),
    ]
