# Generated by Django 5.2.17 on 2026-10-04 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_channel_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredObject',
            fields=[
                ('key', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('remote', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
