# Generated by Django 5.2.17 on 2026-10-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_staff_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconversation',
            name='review',
            field=models.JSONField(default=dict),
        ),
    ]
