# Generated by Django 5.2.17 on 2026-09-22 19:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_pagepreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferVersion',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('offer_id', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=16)),
                ('plan', models.CharField(blank=True, max_length=12)),
                ('name', models.CharField(max_length=80)),
                ('price_xtr', models.PositiveIntegerField(null=True)),
                ('period_seconds', models.PositiveIntegerField(null=True)),
                ('quantities', models.JSONField(default=dict)),
                ('sandbox', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sandbox', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True)),
                ('checked', models.PositiveIntegerField(default=0)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('issues', models.PositiveIntegerField(default=0)),
                ('next_offset', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommerceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=48)),
                ('target', models.CharField(max_length=100)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(default=dict)),
                ('amount_xtr', models.PositiveIntegerField()),
                ('currency', models.CharField(default='XTR', max_length=3)),
                ('status', models.CharField(default='created', max_length=16)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('invoice_url', models.TextField(blank=True)),
                ('sandbox', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.offerversion')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_charge_id', models.CharField(max_length=200, unique=True)),
                ('provider_payment_charge_id', models.CharField(blank=True, max_length=200)),
                ('amount_xtr', models.PositiveIntegerField()),
                ('currency', models.CharField(default='XTR', max_length=3)),
                ('kind', models.CharField(max_length=16)),
                ('plan', models.CharField(blank=True, max_length=12)),
                ('is_renewal', models.BooleanField(default=False)),
                ('sandbox', models.BooleanField(default=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revoked_at', models.DateTimeField(null=True)),
                ('grant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_source', to='core.usagegrant')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_links', to='commerce.payment')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('charge_id', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=64)),
                ('amount_xtr', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='open', max_length=16)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qualified_at', models.DateTimeField(null=True)),
                ('grant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.usagegrant')),
                ('invitee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral_received', to='core.account')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_sent', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_xtr', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='commerce.payment')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.CharField(max_length=24)),
                ('consumed_units', models.PositiveIntegerField()),
                ('reserved_units', models.PositiveIntegerField()),
                ('reason', models.CharField(default='refunded_grant_already_used', max_length=100)),
                ('status', models.CharField(default='review', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.refund')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=12)),
                ('status', models.CharField(default='active', max_length=24)),
                ('renewal_enabled', models.BooleanField(default=True)),
                ('first_charge_id', models.CharField(max_length=200)),
                ('current_period_end', models.DateTimeField()),
                ('scheduled_plan', models.CharField(blank=True, max_length=12)),
                ('scheduled_at', models.DateTimeField(null=True)),
                ('sandbox', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='core.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.invoice')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.offerversion')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=12)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('sandbox', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='period', to='commerce.payment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='commerce.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account')),
                ('sender_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='BotDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(null=True)),
                ('message_id', models.BigIntegerField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.artifact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'idempotency_key'), name='one_bot_delivery_request')],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('account', 'idempotency_key'), name='one_invoice_request'),
        ),
        migrations.AddConstraint(
            model_name='balanceadjustment',
            constraint=models.UniqueConstraint(fields=('refund', 'meter'), name='one_refund_adjustment'),
        ),
    ]
