# Generated by Django 5.2.17 on 2026-09-22 19:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('core', '0004_pagepreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBotMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=8)),
                ('text', models.TextField(blank=True)),
                ('buttons', models.JSONField(default=list)),
                ('telegram_message_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fileasset')),
            ],
        ),
    ]
