# Generated by Django 5.2.17 on 2026-10-02 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_localbotmessage'),
        ('core', '0013_triple_ai_credits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='provider',
            field=models.CharField(default='telegram_stars', max_length=24),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='telegram_stars', max_length=24),
        ),
        migrations.AddField(
            model_name='subscription',
            name='provider',
            field=models.CharField(default='telegram_stars', max_length=24),
        ),
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=12, unique=True)),
                ('plan', models.CharField(max_length=12)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('card', models.JSONField(default=dict)),
                ('status', models.CharField(default='awaiting', max_length=16)),
                ('channel', models.CharField(default='web', max_length=8)),
                ('receipt_key', models.CharField(blank=True, max_length=200)),
                ('receipt_type', models.CharField(blank=True, max_length=40)),
                ('receipt_size', models.PositiveIntegerField(default=0)),
                ('receipt_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('receipt_deleted_at', models.DateTimeField(null=True)),
                ('payer_note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(null=True)),
                ('decided_at', models.DateTimeField(null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_payments', to='core.account')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual', to='commerce.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=24)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(null=True)),
                ('message_id', models.BigIntegerField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='commerce.manualpayment')),
            ],
        ),
        migrations.AddIndex(
            model_name='manualpayment',
            index=models.Index(fields=['status', 'submitted_at'], name='manual_payment_queue'),
        ),
        migrations.AddConstraint(
            model_name='manualpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('awaiting', 'submitted'))), fields=('account',), name='one_open_manual_payment'),
        ),
        migrations.AddIndex(
            model_name='paymentnotice',
            index=models.Index(fields=['status', 'next_attempt_at'], name='payment_notice_due'),
        ),
        migrations.AddConstraint(
            model_name='paymentnotice',
            constraint=models.UniqueConstraint(fields=('manual', 'kind'), name='one_payment_notice'),
        ),
    ]
