# Generated by Django 5.2.17 on 2026-09-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('encrypted_secrets', models.BinaryField(default=bytes)),
                ('configuration', models.JSONField(default=dict)),
                ('checked_at', models.DateTimeField(null=True)),
                ('check_status', models.CharField(default='not_checked', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
