# Generated by Django 5.2.17 on 2026-10-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_integrationconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffTOTP',
        ),
    ]
