# Generated by Django 5.2.17 on 2026-09-22 19:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pagepreview'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_id', models.CharField(max_length=100)),
                ('child_quote_ids', models.JSONField(default=list)),
                ('meters', models.JSONField(default=dict)),
                ('policy', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='BatchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='queued', max_length=24)),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='studio.batchquote')),
            ],
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=24)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.job')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.quote')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='studio.batchrun')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddConstraint(
            model_name='batchrun',
            constraint=models.UniqueConstraint(fields=('account', 'idempotency_key'), name='one_batch_submission'),
        ),
        migrations.AddConstraint(
            model_name='batchitem',
            constraint=models.UniqueConstraint(fields=('run', 'index'), name='one_batch_position'),
        ),
    ]
