# Generated by Django 5.2.17 on 2026-09-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_batchquote_batchrun_batchitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='lease_token',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='lease_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
