# Generated by Django 5.2.17 on 2026-09-22 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_workflow_confirmation_lease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.saveddefinition'),
        ),
    ]
