# Generated by Django 5.2.17 on 2026-09-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_preserve_workflow_history_on_definition_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSearch',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('hits', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
