# Generated by Django 5.2.17 on 2026-09-28 21:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_staff_plan_override'),
        ('studio', '0005_photo_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(default='openai', max_length=24)),
                ('feature_id', models.CharField(max_length=100)),
                ('requested_model', models.CharField(max_length=100)),
                ('resolved_model', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(default='generate', max_length=24)),
                ('span_start', models.PositiveIntegerField(null=True)),
                ('span_end', models.PositiveIntegerField(null=True)),
                ('environment', models.CharField(default='unknown', max_length=16)),
                ('locale', models.CharField(blank=True, max_length=2)),
                ('origin_channel', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(default='started', max_length=16)),
                ('provider_status', models.CharField(blank=True, max_length=24)),
                ('response_id', models.CharField(blank=True, max_length=255)),
                ('response_key', models.CharField(max_length=64, null=True, unique=True)),
                ('duplicate_response', models.BooleanField(default=False)),
                ('input_tokens', models.PositiveBigIntegerField(null=True)),
                ('output_tokens', models.PositiveBigIntegerField(null=True)),
                ('total_tokens', models.PositiveBigIntegerField(null=True)),
                ('cached_input_tokens', models.PositiveBigIntegerField(null=True)),
                ('cache_write_input_tokens', models.PositiveBigIntegerField(null=True)),
                ('reasoning_output_tokens', models.PositiveBigIntegerField(null=True)),
                ('latency_ms', models.PositiveBigIntegerField(null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('duplicate_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='studio.providerattempt')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_attempts', to='core.job')),
            ],
            options={
                'indexes': [models.Index(fields=['environment', 'created_at'], name='provider_attempt_env_date')],
            },
        ),
        migrations.CreateModel(
            name='ProviderCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_hash', models.CharField(max_length=64)),
                ('stage', models.CharField(max_length=24)),
                ('span_start', models.PositiveIntegerField()),
                ('span_end', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('encrypted_result', models.BinaryField(default=bytes)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.generationdraft')),
                ('root_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_checkpoints', to='core.job')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'root_job', 'request_hash'), name='unique_provider_checkpoint')],
            },
        ),
    ]
