# Generated by Django 5.2.17 on 2026-10-04 15:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_channel_membership'),
        ('studio', '0006_providerattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_id', models.CharField(max_length=100)),
                ('channel', models.CharField(blank=True, default='', max_length=16)),
                ('encrypted_request', models.BinaryField()),
                ('output_key', models.CharField(blank=True, default='', max_length=500)),
                ('output_name', models.CharField(blank=True, default='', max_length=255)),
                ('output_mime', models.CharField(blank=True, default='', max_length=120)),
                ('output_size', models.PositiveBigIntegerField(default=0)),
                ('output_pages', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_records', to='core.account')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_record', to='core.job')),
            ],
        ),
    ]
