"""Telegram copy in English, Uzbek and Russian.

Buttons pair a familiar symbol with words; messages keep the next action clear.
Use the same keys and format placeholders in every language.
"""
LOCALES = ('en', 'uz', 'ru')

MESSAGES = {
    'download_error': ('📎 I couldn’t download that file. Please send it again.', '📎 Faylni yuklab bo‘lmadi. Qayta yuboring.', '📎 Не удалось скачать файл. Отправьте его ещё раз.'),
    'wrong_file': ('📎 This file doesn’t match your tool. Send a matching file or choose another tool.', '📎 Fayl bu vositaga mos emas. Mos fayl yuboring yoki boshqa vosita tanlang.', '📎 Файл не подходит для этого инструмента. Отправьте подходящий файл или выберите другой инструмент.'),
    'home_title': ('👋 What shall we do with your document?', '👋 Hujjatingiz bilan nima qilamiz?', '👋 Что сделаем с документом?'),
    'home_body': ('Send a file or choose a tool below.', 'Fayl yuboring yoki quyidan vosita tanlang.', 'Отправьте файл или выберите инструмент.'),
    'home': ('🏠 Main menu', '🏠 Bosh menyu', '🏠 Главное меню'),
    'quick_tools': ('⚡ Quick actions', '⚡ Tezkor amallar', '⚡ Быстрые действия'),
    'all_tools': ('🧰 All tools', '🧰 Barcha vositalar', '🧰 Все инструменты'),
    'pdf_tools': ('📄 PDF tools', '📄 PDF vositalari', '📄 Инструменты PDF'),
    'convert_tools': ('🔄 Convert files', '🔄 Formatni o‘zgartirish', '🔄 Конвертация'),
    'recent': ('🗂 Recent tasks', '🗂 So‘nggi vazifalar', '🗂 Последние задачи'),
    'account': ('👤 My account', '👤 Hisobim', '👤 Мой аккаунт'),
    'help_button': ('💬 Help', '💬 Yordam', '💬 Помощь'),
    'language_button': ('🌐 Language', '🌐 Til', '🌐 Язык'),
    'continue_task': ('▶️ Continue task', '▶️ Davom etish', '▶️ Продолжить'),
    'choose_tool': ('🧰 What would you like to do?', '🧰 Nima qilmoqchisiz?', '🧰 Что нужно сделать?'),
    'choose_pdf_action': ('📄 PDF received. What shall we do?\nTo merge, send another PDF.', '📄 PDF qabul qilindi. Nima qilamiz?\nBirlashtirish uchun yana PDF yuboring.', '📄 PDF получен. Что сделаем?\nДля объединения отправьте ещё один PDF.'),
    'upload_title': ('📎 Send your file', '📎 Fayl yuboring', '📎 Отправьте файл'),
    'replace_file_question': ('📎 Replace the current file?', '📎 Joriy fayl almashtirilsinmi?', '📎 Заменить текущий файл?'),
    'replace_file': ('🔄 Replace file', '🔄 Faylni almashtirish', '🔄 Заменить файл'),
    'keep_file': ('↩️ Keep current file', '↩️ Joriy faylni qoldirish', '↩️ Оставить текущий'),
    'new_tool_question': ('{tool}\nThis tool needs different files. Start a new task? Saved files stay in your account.', '{tool}\nBu vositaga boshqa fayllar kerak. Yangi vazifa boshlaymizmi? Saqlangan fayllar hisobingizda qoladi.', '{tool}\nНужны другие файлы. Начать новую задачу? Сохранённые файлы останутся в аккаунте.'),
    'choose_one_file': ('📎 Which file shall we use?', '📎 Qaysi fayldan foydalanamiz?', '📎 Какой файл используем?'),
    'upload_pdf': ('Attach a PDF, up to 20 MB.', '20 MB gacha PDF yuboring.', 'Прикрепите PDF до 20 МБ.'),
    'upload_merge': ('Send 2 or more PDFs in the order you want. Up to 20 MB each.', 'Kamida 2 ta PDF’ni kerakli tartibda yuboring. Har biri 20 MB gacha.', 'Отправьте от 2 PDF в нужном порядке, до 20 МБ каждый.'),
    'upload_images': ('Send JPG or PNG images, up to 20 MB each. Attach as files for the best quality.', 'JPG yoki PNG yuboring, har biri 20 MB gacha. Sifatni saqlash uchun fayl sifatida yuboring.', 'Отправьте JPG или PNG до 20 МБ каждый. Для лучшего качества прикрепляйте как файлы.'),
    'upload_word': ('Send a Word file (.docx), up to 20 MB.', '20 MB gacha Word fayli (.docx) yuboring.', 'Отправьте файл Word (.docx) до 20 МБ.'),
    'upload_slides': ('Send a PowerPoint file (.pptx), up to 20 MB.', '20 MB gacha PowerPoint fayli (.pptx) yuboring.', 'Отправьте файл PowerPoint (.pptx) до 20 МБ.'),
    'upload_received': ('📎 Files added: {count}. Choose your next step below.', '📎 {count} ta fayl qo‘shildi. Quyidan keyingi amalni tanlang.', '📎 Добавлено файлов: {count}. Выберите действие ниже.'),
    'file_ready': ('📎 Files ready: {count}', '📎 Tayyor fayllar: {count}', '📎 Файлов готово: {count}'),
    'need_more_files': ('📎 Send one more PDF to merge them.', '📎 Birlashtirish uchun yana bitta PDF yuboring.', '📎 Отправьте ещё один PDF для объединения.'),
    'options_title': ('⚙️ Your files & options', '⚙️ Fayllar va sozlamalar', '⚙️ Файлы и настройки'),
    'files': ('Files', 'Fayllar', 'Файлы'),
    'pages': ('Pages', 'Sahifalar', 'Страницы'),
    'original': ('Original size', 'Asl o‘lcham', 'Исходный размер'),
    'options_default': ('Standard settings', 'Standart sozlamalar', 'Стандартные настройки'),
    'options_button': ('⚙️ Options', '⚙️ Sozlamalar', '⚙️ Настройки'),
    'edit_options': ('⚙️ Adjust options', '⚙️ Sozlash', '⚙️ Настроить'),
    'settings_saved': ('✅ Settings updated.', '✅ Sozlamalar saqlandi.', '✅ Настройки сохранены.'),
    'autoquote_not_ready': ('Choose the pages below, then you’re ready to start.', 'Quyidan sahifalarni tanlang, keyin boshlash mumkin.', 'Выберите страницы ниже — и можно начинать.'),
    'page_selection': ('📑 Choose pages', '📑 Sahifalarni tanlash', '📑 Выбрать страницы'),
    'page_order': ('↕️ Page order', '↕️ Sahifalar tartibi', '↕️ Порядок страниц'),
    'split_groups': ('✂️ Page groups', '✂️ Sahifa guruhlari', '✂️ Группы страниц'),
    'all_pages': ('📑 All pages', '📑 Barcha sahifalar', '📑 Все страницы'),
    'each_page': ('📄 Each page separately', '📄 Har sahifa alohida', '📄 Каждая страница отдельно'),
    'file_order': ('↕️ File order', '↕️ Fayllar tartibi', '↕️ Порядок файлов'),
    'remove_file': ('➖ Remove file', '➖ Faylni olib tashlash', '➖ Убрать файл'),
    'margin_button': ('↔️ Margins', '↔️ Hoshiya', '↔️ Поля'),
    'pages_prompt': ('📑 Which pages?\nFor example: 1,3-5', '📑 Qaysi sahifalar?\nMasalan: 1,3-5', '📑 Какие страницы?\nНапример: 1,3-5'),
    'reorder_prompt': ('↕️ Send every page number once, in the new order.\nFor example: 3,1,2', '↕️ Har bir sahifa raqamini yangi tartibda bir marta yozing.\nMasalan: 3,1,2', '↕️ Укажите все страницы по одному разу в новом порядке.\nНапример: 3,1,2'),
    'split_prompt': ('✂️ Send page groups, separated by ;\nFor example: 1-2;3-5', '✂️ Sahifa guruhlarini ; bilan ajratib yozing.\nMasalan: 1-2;3-5', '✂️ Разделите группы страниц знаком ;\nНапример: 1-2;3-5'),
    'order_prompt': ('↕️ Send all file numbers in the new order.\nFor example: 2,1', '↕️ Barcha fayl raqamlarini yangi tartibda yozing.\nMasalan: 2,1', '↕️ Укажите все номера файлов в новом порядке.\nНапример: 2,1'),
    'remove_prompt': ('➖ Which file? Send its number, for example: 2.\nIt stays saved in your account.', '➖ Qaysi fayl? Raqamini yozing, masalan: 2.\nFayl hisobingizda saqlanadi.', '➖ Какой файл убрать? Введите номер, например: 2.\nОн останется в вашем аккаунте.'),
    'margin_prompt': ('↔️ Send a margin from 0 to 72 points.\nFor example: 24', '↔️ Hoshiyani 0–72 punkt oralig‘ida yozing.\nMasalan: 24', '↔️ Укажите размер полей от 0 до 72 пунктов.\nНапример: 24'),
    'review_title': ('✅ Ready to start', '✅ Boshlashga tayyor', '✅ Можно начинать'),
    'review_hint': ('Check the usage below, then tap Start.', 'Quyidagi sarfni tekshirib, Boshlashni bosing.', 'Проверьте расход лимита и нажмите «Начать».'),
    'tap_to_run': ('Your allowance is used only after you tap Start.', 'Limit faqat Boshlashni bosganingizdan keyin sarflanadi.', 'Лимит расходуется только после нажатия «Начать».'),
    'run_cost': ('▶️ Start · {cost}', '▶️ Boshlash · {cost}', '▶️ Начать · {cost}'),
    'cost': ('Will use', 'Sarflanadi', 'Будет списано'),
    'available': ('Available', 'Mavjud', 'Доступно'),
    'file_tasks': ('Tasks', 'Vazifalar', 'Задачи'),
    'page_units': ('Page units', 'Sahifa birliklari', 'Единицы страниц'),
    'ai_credits': ('AI credits', 'AI kreditlar', 'Кредиты ИИ'),
    'edit_settings': ('⚙️ Edit options', '⚙️ Sozlash', '⚙️ Настроить'),
    'cancel_step': ('✖️ Cancel', '✖️ Bekor qilish', '✖️ Отмена'),
    'cancel_button': ('✖️ Cancel task', '✖️ Bekor qilish', '✖️ Отменить задачу'),
    'cancel_question': ('Discard this draft? Your files and submitted tasks will stay saved.', 'Qoralama bekor qilinsinmi? Fayllar va yuborilgan vazifalar saqlanadi.', 'Удалить черновик? Файлы и отправленные задачи сохранятся.'),
    'cancel_confirm': ('🗑 Discard draft', '🗑 Bekor qilish', '🗑 Удалить черновик'),
    'keep_task': ('▶️ Keep working', '▶️ Davom etish', '▶️ Продолжить'),
    'new_question': ('Start fresh? This replaces your draft. Saved files and history stay.', 'Yangidan boshlaymizmi? Qoralama tozalanadi. Fayllar va tarix saqlanadi.', 'Начать заново? Черновик будет заменён. Файлы и история сохранятся.'),
    'new_confirm': ('➕ Start fresh', '➕ Yangidan boshlash', '➕ Начать заново'),
    'new_task': ('➕ New task', '➕ Yangi vazifa', '➕ Новая задача'),
    'processing': ('⏳ Working on it…\nYou can close the chat. I’ll send your result here.', '⏳ Tayyorlayapman…\nChatni yopishingiz mumkin. Natijani shu yerga yuboraman.', '⏳ Обрабатываю…\nМожно закрыть чат. Я пришлю результат сюда.'),
    'check_status': ('🔄 Refresh status', '🔄 Holatni yangilash', '🔄 Обновить статус'),
    'queued': ('⏳ You’re in the queue. I’ll send your result here when it’s ready.', '⏳ Vazifa navbatda. Tayyor natijani shu yerga yuboraman.', '⏳ Задача в очереди. Пришлю результат, когда он будет готов.'),
    'recent_empty': ('🗂 No tasks yet. Send a file to get started.', '🗂 Hali vazifalar yo‘q. Boshlash uchun fayl yuboring.', '🗂 Задач пока нет. Отправьте файл, чтобы начать.'),
    'download': ('📥 Send result again', '📥 Natijani qayta yuborish', '📥 Прислать результат снова'),
    'result_expired': ('⌛ This result is no longer stored. Send the original file to try again.', '⌛ Natijaning saqlash muddati tugagan. Asl faylni qayta yuboring.', '⌛ Срок хранения истёк. Отправьте исходный файл ещё раз.'),
    'retry_task': ('🔄 Review & retry', '🔄 Tekshirib qayta urinish', '🔄 Проверить и повторить'),
    'link_methods': ('🔑 Sign-in methods', '🔑 Kirish usullari', '🔑 Способы входа'),
    'linked_methods': ('Sign in with', 'Kirish usullari', 'Способы входа'),
    'link_instructions': ('Use email or Google already? Sign in to that account on the website → Settings → Sign-in methods → Connect Telegram. Approve here, then return to the same browser.', 'Email yoki Google bilan kirganmisiz? Saytda o‘sha hisobga kiring → Sozlamalar → Kirish usullari → Telegramni ulash. Bu yerda tasdiqlab, o‘sha brauzerga qayting.', 'Уже входите через email или Google? На сайте войдите в тот аккаунт → Настройки → Способы входа → Подключить Telegram. Подтвердите здесь и вернитесь в тот же браузер.'),
    'support_prompt': ('💬 How can we help? Send one message (5–4000 characters).\nKeep passwords, login codes and card details private.', '💬 Qanday yordam kerak? Bitta xabarda yozing (5–4000 belgi).\nParol, kirish kodi va karta ma’lumotlarini yubormang.', '💬 Чем помочь? Напишите одним сообщением (5–4000 символов).\nНе отправляйте пароли, коды входа и данные карты.'),
    'support_confirm': ('💬 Send this to support?', '💬 Yordam xizmatiga yuborilsinmi?', '💬 Отправить в поддержку?'),
    'support_send': ('📨 Send message', '📨 Yuborish', '📨 Отправить'),
    'support_edit': ('✏️ Edit message', '✏️ Tahrirlash', '✏️ Изменить'),
    'support_saved': ('✅ Message sent · #{reference}\nFollow up in the web app.', '✅ Xabar yuborildi · #{reference}\nSuhbatni veb ilovada davom ettiring.', '✅ Сообщение отправлено · #{reference}\nПродолжить переписку можно на сайте.'),
    'support_button': ('💬 Contact support', '💬 Yordamga yozish', '💬 Поддержка'),
    'payment_help': ('💳 Payment help', '💳 To‘lov bo‘yicha yordam', '💳 Помощь с оплатой'),
    'guide': ('📎 Send a file → choose what to do → Start.\n✨ Or tap Create with AI: choose a tool, send your topic in one message, and check the cost before it runs.\n🔒 Enter PDF passwords and edit PDFs in the web app.', '📎 Fayl yuboring → amalni tanlang → Boshlash.\n✨ Yoki «AI bilan yaratish»ni bosing: vosita tanlang, mavzuni bitta xabarda yuboring va narxini tasdiqlang.\n🔒 PDF parollarini kiriting va PDF tahrirlashni veb ilovada bajaring.', '📎 Отправьте файл → выберите действие → Начать.\n✨ Или нажмите «Создать с ИИ»: выберите инструмент, отправьте тему одним сообщением и подтвердите стоимость.\n🔒 Пароли PDF вводите и редактируйте PDF на сайте.'),
    'fallback': ('📎 Send a file or use the buttons below.', '📎 Fayl yuboring yoki quyidagi tugmalardan foydalaning.', '📎 Отправьте файл или выберите кнопку ниже.'),
    'unsupported': ('📎 Please send a PDF, JPG, PNG, Word (.docx) or PowerPoint (.pptx) file.', '📎 PDF, JPG, PNG, Word (.docx) yoki PowerPoint (.pptx) fayli yuboring.', '📎 Отправьте PDF, JPG, PNG, Word (.docx) или PowerPoint (.pptx).'),
    'resend': ('✅ Language saved. Send your file again to begin.', '✅ Til saqlandi. Boshlash uchun faylni qayta yuboring.', '✅ Язык сохранён. Отправьте файл ещё раз, чтобы начать.'),
    'web_tools': ('🌐 More tools on the web', '🌐 Saytda ko‘proq vositalar', '🌐 Больше инструментов на сайте'),
    'web_hint': ('🌐 Open the web app with the same account to edit PDFs and enter passwords securely.', '🌐 PDF tahrirlash va parollarni xavfsiz kiritish uchun shu hisob bilan veb ilovani oching.', '🌐 Откройте сайт с тем же аккаунтом, чтобы редактировать PDF и безопасно вводить пароли.'),
    'upload_more': ('📎 Add files', '📎 Fayl qo‘shish', '📎 Добавить файлы'),
    'one_file_hint': ('📎 This tool takes one file. Remove the extras or start a new task.', '📎 Bu vositaga bitta fayl kerak. Ortiqchasini olib tashlang yoki yangi vazifa boshlang.', '📎 Нужен один файл. Уберите лишние или начните новую задачу.'),
    'photo_hint': ('📷 Photo added. Next time, send as a file to keep the original quality.', '📷 Rasm qo‘shildi. Asl sifatni saqlash uchun keyingi safar fayl sifatida yuboring.', '📷 Фото добавлено. Для исходного качества отправляйте изображение как файл.'),
    'prompt_invalid': ('Try the format in the example, or tap Back.', 'Namunadagi shaklda yozing yoki Orqaga bosing.', 'Попробуйте ввести как в примере или нажмите «Назад».'),
    'free_plan': ('Free', 'Bepul', 'Бесплатный'),
    'resets': ('Resets', 'Yangilanadi', 'Обновится'),
    'plan_label': ('Plan', 'Tarif', 'Тариф'),
    'plans': ('⭐ Plans & packs', '⭐ Tariflar va paketlar', '⭐ Тарифы и пакеты'),
    'usage_button': ('📊 My allowance', '📊 Limitlarim', '📊 Мои лимиты'),
    'subscription': ('💳 Subscription', '💳 Obuna', '💳 Подписка'),
    'quota_hint': ('Your allowance isn’t enough for this task. Use fewer files or pages, or choose a plan.', 'Bu vazifaga limit yetmaydi. Kamroq fayl yoki sahifa tanlang, yoxud tarifni yangilang.', 'Лимита не хватает. Выберите меньше файлов или страниц либо другой тариф.'),
    'limits': ('📎 Bot limit: 20 MB per file. Use the website for larger files.', '📎 Botda: har fayl 20 MB gacha. Kattaroq fayl uchun saytdan foydalaning.', '📎 В боте: до 20 МБ на файл. Для больших файлов используйте сайт.'),
    'retention': ('🕒 Server files are stored for 24 hours. Copies sent here stay in your chat.', '🕒 Server fayllari 24 soat saqlanadi. Bu yerga yuborilgan nusxalar chatda qoladi.', '🕒 Файлы на сервере хранятся 24 часа. Отправленные сюда копии остаются в чате.'),
    # AI generation. The studio's own errors are translated in errors.py.
    'ai_button': ('✨ Create with AI', '✨ AI bilan yaratish', '✨ Создать с ИИ'),
    'ai_home': ('✨ What shall we make?', '✨ Nima yaratamiz?', '✨ Что создадим?'),
    'ai_group_documents': ('📄 Documents & slides', '📄 Hujjat va taqdimot', '📄 Документы и слайды'),
    'ai_group_study': ('📚 Studying', '📚 O‘qish', '📚 Учёба'),
    'ai_group_school': ('🎒 Schoolwork', '🎒 Maktab ishi', '🎒 Школьные задания'),
    'ai_group_teacher': ('🧑‍🏫 Teaching', '🧑‍🏫 Dars berish', '🧑‍🏫 Преподавание'),
    'ai_choose_tool': ('Choose what to make. Everything is made from what you tell me.', 'Nima yaratishni tanlang. Hammasi siz aytgan narsadan tayyorlanadi.', 'Выберите, что создать. Всё делается по тому, что вы напишете.'),
    'ai_ask_topic': ('✍️ Send your topic or instructions in one message.', '✍️ Mavzu yoki ko‘rsatmalaringizni bitta xabarda yuboring.', '✍️ Отправьте тему или указания одним сообщением.'),
    'ai_ask_question': ('❓ Send your question, then the text it should answer from — leave a blank line between them. Or attach a PDF first.', '❓ Savolingizni yuboring, so‘ng javob olinadigan matnni — orasida bo‘sh qator qoldiring. Yoki avval PDF biriktiring.', '❓ Отправьте вопрос, затем текст, по которому отвечать — через пустую строку. Или сначала прикрепите PDF.'),
    'ai_ask_file': ('✍️ Paste or type your material in one message — or attach a PDF instead.', '✍️ Materialingizni bitta xabarda yuboring — yoki PDF biriktiring.', '✍️ Отправьте материал одним сообщением — или прикрепите PDF.'),
    'ai_ask_photo': ('📷 Send a photo of the handwritten page.', '📷 Qo‘lyozma sahifaning suratini yuboring.', '📷 Отправьте фото рукописной страницы.'),
    'ai_topic_hint': ('Longer instructions give a better result.', 'Batafsil ko‘rsatma yaxshiroq natija beradi.', 'Чем подробнее указания, тем лучше результат.'),
    'ai_topic_empty': ('✍️ I need a topic or instructions before I can start.', '✍️ Boshlashim uchun mavzu yoki ko‘rsatma kerak.', '✍️ Чтобы начать, нужна тема или указания.'),
    'ai_preparing': ('⏳ Preparing your draft…', '⏳ Qoralama tayyorlanmoqda…', '⏳ Готовлю черновик…'),
    'ai_generate': ('✨ Generate', '✨ Yaratish', '✨ Создать'),
    'ai_change_topic': ('✏️ Change the topic', '✏️ Mavzuni o‘zgartirish', '✏️ Изменить тему'),
    'ai_review_hint': ('Nothing is charged until you tap Generate.', '«Yaratish» tugmasini bosmaguningizcha hech narsa hisoblanmaydi.', 'Ничего не списывается, пока вы не нажмёте «Создать».'),
    'ai_sources': ('From your files', 'Fayllaringizdan', 'Из ваших файлов'),
    'ai_web_only': ('🖥 This one is built on what you have already made in the web app. Open it there to continue.', '🖥 Bu vosita veb ilovada tayyorlagan ishlaringizga asoslanadi. Davom etish uchun o‘sha yerda oching.', '🖥 Этот инструмент работает с тем, что вы уже сделали в веб-приложении. Откройте его там.'),
    'ai_needs_file': ('📎 This tool needs a document. Send a PDF and try again.', '📎 Bu vosita uchun hujjat kerak. PDF yuboring va qayta urinib ko‘ring.', '📎 Для этого инструмента нужен документ. Отправьте PDF и повторите.'),
    'ai_more': ('▶️ More tools', '▶️ Yana vositalar', '▶️ Ещё инструменты'),
    'ai_continue': ('✨ Use this photo', '✨ Shu surat bilan davom etish', '✨ Продолжить с этим фото'),
    'ai_back': ('◀️ Back', '◀️ Orqaga', '◀️ Назад'),
    'ai_open_web': ('🌐 Open in web app', '🌐 Veb ilovada ochish', '🌐 Открыть в веб-приложении'),
    'ai_busy': ('⏳ One moment — still working on your last request.', '⏳ Bir lahza — oldingi so‘rovingiz ustida ishlanmoqda.', '⏳ Секунду — ещё обрабатываю прошлый запрос.'),
}

# Keep the older keys for commands, saved controls and transport compatibility.
# They share the same tone as the primary flow instead of exposing command syntax.
LEGACY_MESSAGES = {
    'welcome': ('👋 Welcome to PDF Master! Send a file to begin. Server copies are kept for 24 hours.', '👋 PDF Master’ga xush kelibsiz! Boshlash uchun fayl yuboring. Serverdagi nusxalar 24 soat saqlanadi.', '👋 Добро пожаловать в PDF Master! Отправьте файл. Копии на сервере хранятся 24 часа.'),
    'tools': ('🧰 Choose what to do with your file.', '🧰 Fayl bilan nima qilishni tanlang.', '🧰 Выберите действие с файлом.'),
    'received': ('📎 File added. Send more or tap Start when ready.', '📎 Fayl qo‘shildi. Yana yuboring yoki Boshlashni bosing.', '📎 Файл добавлен. Отправьте ещё или нажмите «Начать».'),
    'done': ('✅ Check your files and usage, then tap Start.', '✅ Fayllar va sarfni tekshirib, Boshlashni bosing.', '✅ Проверьте файлы и расход лимита, затем нажмите «Начать».'),
    'run': ('▶️ Start', '▶️ Boshlash', '▶️ Начать'),
    'empty': ('📎 Send a file first.', '📎 Avval fayl yuboring.', '📎 Сначала отправьте файл.'),
    'working': ('⏳ Working on your file…', '⏳ Fayl tayyorlanmoqda…', '⏳ Обрабатываю файл…'),
    'result': ('✅ Your result is ready! Server copies expire after 24 hours; files sent here stay in the chat.', '✅ Natija tayyor! Serverdagi nusxalar 24 soatdan keyin o‘chiriladi; bu yerdagi fayllar chatda qoladi.', '✅ Готово! Копии на сервере удалятся через 24 часа; присланные файлы останутся в чате.'),
    'no_op': ('✅ Your file is unchanged. No allowance was used.', '✅ Fayl o‘zgarmadi. Limit sarflanmadi.', '✅ Файл не изменился. Лимит не списан.'),
    'support': ('💬 Tell us what you need help with.', '💬 Qanday yordam kerakligini yozing.', '💬 Напишите, с чем нужна помощь.'),
    'ticket': ('✅ Your message is with support.', '✅ Xabaringiz yordam xizmatiga yuborildi.', '✅ Сообщение передано в поддержку.'),
    'cancel': ('✅ Draft discarded. Your files and task history are saved.', '✅ Qoralama bekor qilindi. Fayllar va vazifalar tarixi saqlandi.', '✅ Черновик удалён. Файлы и история задач сохранены.'),
    'help': ('📎 Send a file → choose an action → Start. Use the buttons to adjust options or find recent results.', '📎 Fayl yuboring → amalni tanlang → Boshlash. Sozlamalar va natijalar uchun tugmalardan foydalaning.', '📎 Отправьте файл → выберите действие → Начать. Настройки и результаты доступны по кнопкам.'),
    'login': ('🔐 Approve sign-in only if you requested it in this browser:', '🔐 Faqat ushbu brauzerda kirishni o‘zingiz boshlagan bo‘lsangiz, tasdiqlang:', '🔐 Подтверждайте вход, только если вы запросили его в этом браузере:'),
    'confirm': ('🔐 Approve sign-in', '🔐 Kirishni tasdiqlash', '🔐 Подтвердить вход'),
    'approved': ('✅ Sign-in approved. Return to the same browser.', '✅ Kirish tasdiqlandi. O‘sha brauzerga qayting.', '✅ Вход подтверждён. Вернитесь в тот же браузер.'),
    'language': ('🌐 Choose your language.', '🌐 Tilni tanlang.', '🌐 Выберите язык.'),
    'open': ('🌐 Open web app', '🌐 Veb ilova', '🌐 Открыть сайт'),
    'terms': ('🕒 Server files expire after 24 hours; copies sent to Telegram stay in your chat.\n⭐ Purchases activate after payment is confirmed. Test mode spends no real Stars.\nPayment help: /paysupport', '🕒 Server fayllari 24 soatdan keyin o‘chiriladi; Telegram’ga yuborilgan nusxalar chatda qoladi.\n⭐ Xarid to‘lov tasdiqlangach faollashadi. Sinovda haqiqiy Stars sarflanmaydi.\nTo‘lov yordami: /paysupport', '🕒 Файлы сервера удаляются через 24 часа; копии в Telegram остаются в чате.\n⭐ Покупки активируются после подтверждения оплаты. В тестовом режиме настоящие Stars не тратятся.\nПомощь с оплатой: /paysupport'),
    'settings': ('⚙️ Task options', '⚙️ Vazifa sozlamalari', '⚙️ Настройки задачи'),
    'done_button': ('✅ Review & start', '✅ Tekshirish va boshlash', '✅ Проверить и начать'),
    'back': ('← Back', '← Orqaga', '← Назад'),
    'next': ('🧰 More tools', '🧰 Boshqa vositalar', '🧰 Ещё инструменты'),
    'pages_hint': ('📑 Choose pages, for example: 1,3-5.', '📑 Sahifalarni tanlang, masalan: 1,3-5.', '📑 Выберите страницы, например: 1,3-5.'),
    'split_hint': ('✂️ Choose page groups, or save each page separately.', '✂️ Sahifa guruhlarini tanlang yoki har sahifani alohida saqlang.', '✂️ Выберите группы страниц или сохраните каждую отдельно.'),
    'reorder_hint': ('↕️ Set the order of all pages, for example: 3,1,2.', '↕️ Barcha sahifalar tartibini yozing, masalan: 3,1,2.', '↕️ Задайте порядок всех страниц, например: 3,1,2.'),
    'merge_hint': ('↕️ Files merge in the order shown. You can change it below.', '↕️ Fayllar shu tartibda birlashadi. Quyida o‘zgartirishingiz mumkin.', '↕️ Файлы объединятся в указанном порядке. Его можно изменить ниже.'),
    'image_hint': ('⚙️ Adjust the paper, orientation or margins if needed.', '⚙️ Kerak bo‘lsa qog‘oz, yo‘nalish yoki hoshiyani sozlang.', '⚙️ При желании настройте бумагу, ориентацию и поля.'),
    'secure': ('🔒 Enter PDF passwords only in the web app. Please don’t send them here.', '🔒 PDF parollarini faqat veb ilovada kiriting. Bu chatga yubormang.', '🔒 Вводите пароли PDF только на сайте. Не отправляйте их сюда.'),
    'rotate_label': ('Rotation', 'Aylantirish', 'Поворот'),
    'format_label': ('Image format', 'Rasm formati', 'Формат изображения'),
    'paper_label': ('Paper size', 'Qog‘oz o‘lchami', 'Размер бумаги'),
    'portrait': ('↕️ Portrait', '↕️ Tik', '↕️ Книжная'),
    'landscape': ('↔️ Landscape', '↔️ Yotiq', '↔️ Альбомная'),
    'auto': ('✨ Auto', '✨ Avtomatik', '✨ Авто'),
    'quote_cost': ('Tasks / page units', 'Vazifa / sahifa birligi', 'Задачи / единицы страниц'),
    'balance': ('Available tasks / page units', 'Mavjud vazifa / sahifa birligi', 'Доступно задач / единиц страниц'),
    'expires': ('Valid until (UTC)', 'Amal qiladi (UTC)', 'Действует до (UTC)'),
    'parameters': ('Options', 'Sozlamalar', 'Настройки'),
    'add': ('📎 Add to this task', '📎 Shu vazifaga qo‘shish', '📎 Добавить к задаче'),
    'new': ('➕ New task', '➕ Yangi vazifa', '➕ Новая задача'),
    'new_file': ('📎 Add this file to your draft, or start fresh?', '📎 Faylni qoralamaga qo‘shamizmi yoki yangidan boshlaymizmi?', '📎 Добавить файл к черновику или начать заново?'),
    'controls_expired': ('This button is out of date. Use the latest buttons or /menu.', 'Bu tugma eskirgan. Oxirgi tugmalardan foydalaning yoki /menu yuboring.', 'Эта кнопка устарела. Используйте последние кнопки или /menu.'),
    'no_preview': ('A preview isn’t available. You can still process the file.', 'Ko‘rib chiqish imkoni yo‘q. Fayl bilan ishlashni davom ettirishingiz mumkin.', 'Предпросмотр недоступен. Файл всё равно можно обработать.'),
    'preview': ('👁 Preview page 1', '👁 1-sahifani ko‘rish', '👁 Посмотреть страницу 1'),
    'link_login': ('🔗 Connect Telegram to your existing PDF Master account? Approve only if you started this in account settings:', '🔗 Telegramni mavjud PDF Master hisobingizga ulaymizmi? Faqat hisob sozlamalarida o‘zingiz boshlagan bo‘lsangiz, tasdiqlang:', '🔗 Подключить Telegram к вашему аккаунту PDF Master? Подтверждайте, только если вы начали это в настройках аккаунта:'),
    'link_confirm': ('🔗 Connect Telegram', '🔗 Telegramni ulash', '🔗 Подключить Telegram'),
    'link_approved': ('✅ Telegram approved. Return to the same browser to finish linking.', '✅ Telegram tasdiqlandi. Ulashni tugatish uchun o‘sha brauzerga qayting.', '✅ Telegram подтверждён. Вернитесь в тот же браузер, чтобы завершить привязку.'),
}

TOOL_LABELS = {
    'pdf.merge': ('📑 Merge PDFs', '📑 PDF birlashtirish', '📑 Объединить PDF'),
    'pdf.compress': ('🗜 Compress PDF', '🗜 PDF hajmini kamaytirish', '🗜 Сжать PDF'),
    'pdf.split': ('✂️ Split PDF', '✂️ PDF bo‘lish', '✂️ Разделить PDF'),
    'pdf.extract_pages': ('📑 Extract pages', '📑 Sahifalarni ajratish', '📑 Извлечь страницы'),
    'pdf.delete_pages': ('🗑 Delete pages', '🗑 Sahifalarni o‘chirish', '🗑 Удалить страницы'),
    'pdf.reorder': ('↕️ Reorder pages', '↕️ Sahifalar tartibi', '↕️ Порядок страниц'),
    'pdf.rotate': ('🔄 Rotate pages', '🔄 Sahifalarni aylantirish', '🔄 Повернуть страницы'),
    'pdf.images_to_pdf': ('🖼 Images → PDF', '🖼 Rasmlar → PDF', '🖼 Фото → PDF'),
    'pdf.to_images': ('🖼 PDF → images', '🖼 PDF → rasmlar', '🖼 PDF → изображения'),
    'convert.word_to_pdf': ('📝 Word → PDF', '📝 Word → PDF', '📝 Word → PDF'),
    'convert.pptx_to_pdf': ('📊 PowerPoint → PDF', '📊 PowerPoint → PDF', '📊 PowerPoint → PDF'),
    # Generation features. Names are kept in step with the web app's
    # locales/extended.ts so the same tool reads the same on both surfaces.
    'ai.images': ('🖼 Supporting illustrations', '🖼 Qo‘shimcha rasmlar', '🖼 Иллюстрации'),
    'ai.pdf_sources': ('✨ Document from sources', '✨ Manbalardan hujjat', '✨ Документ по источникам'),
    'ai.pdf_text': ('✨ Format your text', '✨ Matnni formatlash', '✨ Оформить текст'),
    'ai.pdf_topic': ('✨ Document from a topic', '✨ Mavzudan hujjat', '✨ Документ по теме'),
    'ai.pptx': ('📊 Editable presentation', '📊 Tahrirlanadigan taqdimot', '📊 Редактируемая презентация'),
    'ai.regenerate_slide': ('📊 Revise selected slides', '📊 Tanlangan slaydlarni tahrirlash', '📊 Изменить выбранные слайды'),
    'ai.rewrite': ('✨ Rewrite content', '✨ Matnni qayta yozish', '✨ Переписать содержание'),
    'ai.source_to_slides': ('📊 Sources to slides', '📊 Manbalardan slaydlar', '📊 Слайды по источникам'),
    'school.adaptive': ('🎒 Follow-up practice', '🎒 Keyingi mashqlar', '🎒 Практика по результатам'),
    'school.check_attempt': ('✅ Review an attempt', '✅ Urinishni tekshirish', '✅ Проверить попытку'),
    'school.examples': ('🎒 Examples & checks', '🎒 Misollar va tekshiruvlar', '🎒 Примеры и проверка'),
    'school.explain': ('🎒 Explain a lesson', '🎒 Darsni tushuntirish', '🎒 Объяснить урок'),
    'school.hints': ('🎒 Step-by-step hints', '🎒 Bosqichma-bosqich maslahatlar', '🎒 Пошаговые подсказки'),
    'school.poster': ('📊 Project poster', '📊 Loyiha posteri', '📊 Плакат проекта'),
    'school.project_outline': ('🗓 Project outline', '🗓 Loyiha rejasi', '🗓 План проекта'),
    'school.project_slides': ('📊 Project presentation', '📊 Loyiha taqdimoti', '📊 Презентация проекта'),
    'school.reading': ('🎒 Reading practice', '🎒 O‘qish mashqlari', '🎒 Практика чтения'),
    'school.similar_problems': ('🎒 Similar practice problems', '🎒 O‘xshash mashqlar', '🎒 Похожие задачи'),
    'school.vocabulary': ('🗂 Vocabulary exercises', '🗂 Lug‘at mashqlari', '🗂 Словарные упражнения'),
    'school.weekly_pack': ('🎒 Weekly practice pack', '🎒 Haftalik mashq to‘plami', '🎒 Недельный набор заданий'),
    'school.worksheets': ('🎒 Practice worksheets', '🎒 Mashq varaqalari', '🎒 Рабочие листы'),
    'study.answer_key': ('✅ Answers & explanations', '✅ Javoblar va tushuntirishlar', '✅ Ответы и объяснения'),
    'study.definitions': ('🗂 Definitions & key points', '🗂 Ta’riflar va muhim fikrlar', '🗂 Определения и главное'),
    'study.exam_pack': ('📚 Exam preparation pack', '📚 Imtihonga tayyorgarlik to‘plami', '📚 Подготовка к экзамену'),
    'study.flashcards': ('🗂 Flashcards', '🗂 Yodlash kartalari', '🗂 Карточки'),
    'study.handwriting': ('✍️ Review handwritten notes', '✍️ Qo‘lyozma qaydlarni tekshirish', '✍️ Проверить рукописные записи'),
    'study.pdf_qa': ('📚 Questions about a PDF', '📚 PDF bo‘yicha savollar', '📚 Вопросы по PDF'),
    'study.quiz': ('✅ Practice quiz', '✅ Mashq testi', '✅ Тренировочный тест'),
    'study.references': ('📚 Format references', '📚 Manbalar ro‘yxatini formatlash', '📚 Оформить список источников'),
    'study.report_format': ('📚 Format a report', '📚 Hisobotni formatlash', '📚 Оформить отчёт'),
    'study.revision_plan': ('🗓 Revision schedule', '🗓 Takrorlash jadvali', '🗓 План повторения'),
    'study.summary': ('📚 Study summary', '📚 O‘quv xulosasi', '📚 Учебное резюме'),
    'study.writing_feedback': ('📚 Writing feedback', '📚 Yozma ishga fikr', '📚 Обратная связь по тексту'),
    'teacher.answer_key': ('✅ Teacher answer key', '✅ O‘qituvchi uchun javoblar', '✅ Ответы для учителя'),
    'teacher.differentiated': ('🧑‍🏫 Differentiated worksheets', '🧑‍🏫 Darajalangan varaqalar', '🧑‍🏫 Листы разного уровня'),
    'teacher.feedback': ('🧑‍🏫 Draft learner feedback', '🧑‍🏫 O‘quvchiga fikr qoralamasi', '🧑‍🏫 Черновик обратной связи'),
    'teacher.homework': ('🧑‍🏫 Homework activities', '🧑‍🏫 Uy vazifalari', '🧑‍🏫 Домашние задания'),
    'teacher.lesson_pack': ('🧑‍🏫 Complete lesson pack', '🧑‍🏫 To‘liq dars to‘plami', '🧑‍🏫 Полный комплект урока'),
    'teacher.lesson_plan': ('🗓 Lesson plan', '🗓 Dars rejasi', '🗓 План урока'),
    'teacher.mcq': ('✅ Multiple-choice quiz', '✅ Variantli test', '✅ Тест с выбором ответа'),
    'teacher.reading_level': ('🧑‍🏫 Adjust reading level', '🧑‍🏫 O‘qish darajasini moslash', '🧑‍🏫 Адаптировать уровень чтения'),
    'teacher.rubric': ('✅ Assessment rubric', '✅ Baholash mezonlari', '✅ Критерии оценивания'),
    'teacher.suggest_marks': ('✅ Draft marks for review', '✅ Tekshirish uchun baholar', '✅ Предварительные оценки'),
    'teacher.syllabus': ('🗓 Syllabus to teaching plan', '🗓 Dasturdan dars rejasiga', '🗓 Программа в план занятий'),
    'teacher.variants': ('🧑‍🏫 Test variants', '🧑‍🏫 Test variantlari', '🧑‍🏫 Варианты теста'),
    'teacher.worksheet': ('🧑‍🏫 Worksheet', '🧑‍🏫 Ish varaqasi', '🧑‍🏫 Рабочий лист'),
    'teacher.written_test': ('✅ Written test', '✅ Yozma test', '✅ Письменный тест'),
}

UX = {locale: {key: values[index] for key, values in MESSAGES.items()} for index, locale in enumerate(LOCALES)}
LEGACY_COPY = {locale: {key: values[index] for key, values in LEGACY_MESSAGES.items()} for index, locale in enumerate(LOCALES)}
TOOL_NAMES = {key: dict(zip(LOCALES, labels)) for key, labels in TOOL_LABELS.items()}
STATUS = {
    'en': {'queued': '⏳ Queued', 'running': '⚙️ Processing', 'finalizing': '📦 Finishing', 'succeeded': '✅ Ready', 'failed': '⚠️ Couldn’t finish', 'canceled': '✖️ Cancelled', 'expired': '⌛ Expired', 'no_op': '✅ No change'},
    'uz': {'queued': '⏳ Navbatda', 'running': '⚙️ Tayyorlanmoqda', 'finalizing': '📦 Yakunlanmoqda', 'succeeded': '✅ Tayyor', 'failed': '⚠️ Bajarilmadi', 'canceled': '✖️ Bekor qilindi', 'expired': '⌛ Muddati tugagan', 'no_op': '✅ O‘zgarish yo‘q'},
    'ru': {'queued': '⏳ В очереди', 'running': '⚙️ Обработка', 'finalizing': '📦 Завершение', 'succeeded': '✅ Готово', 'failed': '⚠️ Не удалось завершить', 'canceled': '✖️ Отменено', 'expired': '⌛ Срок истёк', 'no_op': '✅ Без изменений'},
}
