"""Telegram copy in English, Uzbek and Russian.

Buttons pair a familiar symbol with words; messages keep the next action clear.
Use the same keys and format placeholders in every language.
"""
LOCALES = ('en', 'uz', 'ru')

MESSAGES = {
    'download_error': ('📎 I couldn’t download that file. Please send it again.', '📎 Faylni yuklab bo‘lmadi. Qayta yuboring.', '📎 Не удалось скачать файл. Отправьте его ещё раз.'),
    'wrong_file': ('📎 This file doesn’t match your tool. Send a matching file or choose another tool.', '📎 Fayl bu vositaga mos emas. Mos fayl yuboring yoki boshqa vosita tanlang.', '📎 Файл не подходит для этого инструмента. Отправьте подходящий файл или выберите другой инструмент.'),
    'home_title': ('👋 What shall we do with your document?', '👋 Hujjatingiz bilan nima qilamiz?', '👋 Что сделаем с документом?'),
    'home_body': ('Send a file or choose a tool below.', 'Fayl yuboring yoki quyidan vosita tanlang.', 'Отправьте файл или выберите инструмент.'),
    'home': ('🏠 Main menu', '🏠 Bosh menyu', '🏠 Главное меню'),
    'quick_tools': ('⚡ Quick actions', '⚡ Tezkor amallar', '⚡ Быстрые действия'),
    'all_tools': ('🧰 All tools', '🧰 Barcha vositalar', '🧰 Все инструменты'),
    'pdf_tools': ('📄 PDF tools', '📄 PDF vositalari', '📄 Инструменты PDF'),
    'convert_tools': ('🔄 Convert files', '🔄 Formatni o‘zgartirish', '🔄 Конвертация'),
    'recent': ('🗂 Recent tasks', '🗂 So‘nggi vazifalar', '🗂 Последние задачи'),
    'account': ('👤 My account', '👤 Hisobim', '👤 Мой аккаунт'),
    'language_button': ('🌐 Language', '🌐 Til', '🌐 Язык'),
    'continue_task': ('▶️ Continue task', '▶️ Davom etish', '▶️ Продолжить'),
    'choose_tool': ('🧰 What would you like to do?', '🧰 Nima qilmoqchisiz?', '🧰 Что нужно сделать?'),
    'choose_pdf_action': ('📄 PDF received. What shall we do?\nTo merge, send another PDF.', '📄 PDF qabul qilindi. Nima qilamiz?\nBirlashtirish uchun yana PDF yuboring.', '📄 PDF получен. Что сделаем?\nДля объединения отправьте ещё один PDF.'),
    'upload_title': ('📎 Send your file', '📎 Fayl yuboring', '📎 Отправьте файл'),
    'replace_file_question': ('📎 Replace the current file?', '📎 Joriy fayl almashtirilsinmi?', '📎 Заменить текущий файл?'),
    'replace_file': ('🔄 Replace file', '🔄 Faylni almashtirish', '🔄 Заменить файл'),
    'keep_file': ('↩️ Keep current file', '↩️ Joriy faylni qoldirish', '↩️ Оставить текущий'),
    'new_tool_question': ('{tool}\nThis tool needs different files. Start a new task? Saved files stay in your account.', '{tool}\nBu vositaga boshqa fayllar kerak. Yangi vazifa boshlaymizmi? Saqlangan fayllar hisobingizda qoladi.', '{tool}\nНужны другие файлы. Начать новую задачу? Сохранённые файлы останутся в аккаунте.'),
    'choose_one_file': ('📎 Which file shall we use?', '📎 Qaysi fayldan foydalanamiz?', '📎 Какой файл используем?'),
    'upload_pdf': ('Attach a PDF, up to 20 MB.', '20 MB gacha PDF yuboring.', 'Прикрепите PDF до 20 МБ.'),
    'upload_merge': ('Send 2 or more PDFs in the order you want. Up to 20 MB each.', 'Kamida 2 ta PDF’ni kerakli tartibda yuboring. Har biri 20 MB gacha.', 'Отправьте от 2 PDF в нужном порядке, до 20 МБ каждый.'),
    'upload_images': ('Send JPG or PNG images, up to 20 MB each. Attach as files for the best quality.', 'JPG yoki PNG yuboring, har biri 20 MB gacha. Sifatni saqlash uchun fayl sifatida yuboring.', 'Отправьте JPG или PNG до 20 МБ каждый. Для лучшего качества прикрепляйте как файлы.'),
    'document_scan_hint': ('Crop & straighten removes the surrounding background. Enhance text makes writing clearer.', 'Kesish va tekislash qog‘oz atrofidagi fonni olib tashlaydi. Matnni tiniqlash yozuvni ravshan qiladi.', 'Обрезка и выравнивание убирают фон вокруг листа. Улучшение текста делает надписи чётче.'),
    'auto_crop_label': ('📐 Crop & straighten', '📐 Kesish va tekislash', '📐 Обрезка и выравнивание'),
    'enhance_text_label': ('✨ Enhance text', '✨ Matnni tiniqlash', '✨ Улучшение текста'),
    'option_on': ('On', 'Yoqilgan', 'Вкл.'),
    'option_off': ('Off', 'O‘chirilgan', 'Выкл.'),
    'upload_word': ('Send a Word file (.docx), up to 20 MB.', '20 MB gacha Word fayli (.docx) yuboring.', 'Отправьте файл Word (.docx) до 20 МБ.'),
    'upload_slides': ('Send a PowerPoint file (.pptx), up to 20 MB.', '20 MB gacha PowerPoint fayli (.pptx) yuboring.', 'Отправьте файл PowerPoint (.pptx) до 20 МБ.'),
    'upload_received': ('📎 Files added: {count}. Choose your next step below.', '📎 {count} ta fayl qo‘shildi. Quyidan keyingi amalni tanlang.', '📎 Добавлено файлов: {count}. Выберите действие ниже.'),
    'file_ready': ('📎 Files ready: {count}', '📎 Tayyor fayllar: {count}', '📎 Файлов готово: {count}'),
    'need_more_files': ('📎 Send one more PDF to merge them.', '📎 Birlashtirish uchun yana bitta PDF yuboring.', '📎 Отправьте ещё один PDF для объединения.'),
    'options_title': ('⚙️ Your files & options', '⚙️ Fayllar va sozlamalar', '⚙️ Файлы и настройки'),
    'files': ('Files', 'Fayllar', 'Файлы'),
    'pages': ('Pages', 'Sahifalar', 'Страницы'),
    'original': ('Original size', 'Asl o‘lcham', 'Исходный размер'),
    'fit_page': ('Fit image', 'Rasmga mos', 'По размеру фото'),
    'options_default': ('Standard settings', 'Standart sozlamalar', 'Стандартные настройки'),
    'options_button': ('⚙️ Options', '⚙️ Sozlamalar', '⚙️ Настройки'),
    'edit_options': ('⚙️ Adjust options', '⚙️ Sozlash', '⚙️ Настроить'),
    'settings_saved': ('✅ Settings updated.', '✅ Sozlamalar saqlandi.', '✅ Настройки сохранены.'),
    'autoquote_not_ready': ('Choose the pages below, then you’re ready to start.', 'Quyidan sahifalarni tanlang, keyin boshlash mumkin.', 'Выберите страницы ниже — и можно начинать.'),
    'page_selection': ('📑 Choose pages', '📑 Sahifalarni tanlash', '📑 Выбрать страницы'),
    'page_order': ('↕️ Page order', '↕️ Sahifalar tartibi', '↕️ Порядок страниц'),
    'split_groups': ('✂️ Page groups', '✂️ Sahifa guruhlari', '✂️ Группы страниц'),
    'all_pages': ('📑 All pages', '📑 Barcha sahifalar', '📑 Все страницы'),
    'each_page': ('📄 Each page separately', '📄 Har sahifa alohida', '📄 Каждая страница отдельно'),
    'file_order': ('↕️ File order', '↕️ Fayllar tartibi', '↕️ Порядок файлов'),
    'remove_file': ('➖ Remove file', '➖ Faylni olib tashlash', '➖ Убрать файл'),
    'margin_button': ('↔️ Margins', '↔️ Hoshiya', '↔️ Поля'),
    'pages_prompt': ('📑 Which pages?\nFor example: 1,3-5', '📑 Qaysi sahifalar?\nMasalan: 1,3-5', '📑 Какие страницы?\nНапример: 1,3-5'),
    'reorder_prompt': ('↕️ Send every page number once, in the new order.\nFor example: 3,1,2', '↕️ Har bir sahifa raqamini yangi tartibda bir marta yozing.\nMasalan: 3,1,2', '↕️ Укажите все страницы по одному разу в новом порядке.\nНапример: 3,1,2'),
    'split_prompt': ('✂️ Send page groups, separated by ;\nFor example: 1-2;3-5', '✂️ Sahifa guruhlarini ; bilan ajratib yozing.\nMasalan: 1-2;3-5', '✂️ Разделите группы страниц знаком ;\nНапример: 1-2;3-5'),
    'order_prompt': ('↕️ Send all file numbers in the new order.\nFor example: 2,1', '↕️ Barcha fayl raqamlarini yangi tartibda yozing.\nMasalan: 2,1', '↕️ Укажите все номера файлов в новом порядке.\nНапример: 2,1'),
    'remove_prompt': ('➖ Which file? Send its number, for example: 2.\nIt stays saved in your account.', '➖ Qaysi fayl? Raqamini yozing, masalan: 2.\nFayl hisobingizda saqlanadi.', '➖ Какой файл убрать? Введите номер, например: 2.\nОн останется в вашем аккаунте.'),
    'margin_prompt': ('↔️ Send a margin from 0 to 72 points.\nFor example: 24', '↔️ Hoshiyani 0–72 punkt oralig‘ida yozing.\nMasalan: 24', '↔️ Укажите размер полей от 0 до 72 пунктов.\nНапример: 24'),
    'review_title': ('✅ Ready to start', '✅ Boshlashga tayyor', '✅ Можно начинать'),
    'review_hint': ('Check the usage below, then tap Start.', 'Quyidagi sarfni tekshirib, Boshlashni bosing.', 'Проверьте расход лимита и нажмите «Начать».'),
    'tap_to_run': ('Your allowance is used only after you tap Start.', 'Limit faqat Boshlashni bosganingizdan keyin sarflanadi.', 'Лимит расходуется только после нажатия «Начать».'),
    'run_cost': ('▶️ Start · {cost}', '▶️ Boshlash · {cost}', '▶️ Начать · {cost}'),
    'cost': ('Will use', 'Sarflanadi', 'Будет списано'),
    'available': ('Available', 'Mavjud', 'Доступно'),
    'file_tasks': ('Tasks', 'Vazifalar', 'Задачи'),
    'page_units': ('Page units', 'Sahifa birliklari', 'Единицы страниц'),
    'ai_credits': ('AI credits', 'AI kreditlar', 'Кредиты ИИ'),
    'edit_settings': ('⚙️ Edit options', '⚙️ Sozlash', '⚙️ Настроить'),
    'cancel_step': ('✖️ Cancel', '✖️ Bekor qilish', '✖️ Отмена'),
    'cancel_button': ('✖️ Cancel task', '✖️ Bekor qilish', '✖️ Отменить задачу'),
    'cancel_question': ('Discard this draft? Your files and submitted tasks will stay saved.', 'Qoralama bekor qilinsinmi? Fayllar va yuborilgan vazifalar saqlanadi.', 'Удалить черновик? Файлы и отправленные задачи сохранятся.'),
    'cancel_confirm': ('🗑 Discard draft', '🗑 Bekor qilish', '🗑 Удалить черновик'),
    'keep_task': ('▶️ Keep working', '▶️ Davom etish', '▶️ Продолжить'),
    'new_question': ('Start fresh? This replaces your draft. Saved files and history stay.', 'Yangidan boshlaymizmi? Qoralama tozalanadi. Fayllar va tarix saqlanadi.', 'Начать заново? Черновик будет заменён. Файлы и история сохранятся.'),
    'new_confirm': ('➕ Start fresh', '➕ Yangidan boshlash', '➕ Начать заново'),
    'new_task': ('➕ New task', '➕ Yangi vazifa', '➕ Новая задача'),
    'processing': ('⏳ Working on it…\nYou can close the chat. I’ll send your result here.', '⏳ Tayyorlayapman…\nChatni yopishingiz mumkin. Natijani shu yerga yuboraman.', '⏳ Обрабатываю…\nМожно закрыть чат. Я пришлю результат сюда.'),
    'check_status': ('🔄 Refresh status', '🔄 Holatni yangilash', '🔄 Обновить статус'),
    'queued': ('⏳ You’re in the queue. I’ll send your result here when it’s ready.', '⏳ Vazifa navbatda. Tayyor natijani shu yerga yuboraman.', '⏳ Задача в очереди. Пришлю результат, когда он будет готов.'),
    'recent_empty': ('🗂 No tasks yet. Send a file to get started.', '🗂 Hali vazifalar yo‘q. Boshlash uchun fayl yuboring.', '🗂 Задач пока нет. Отправьте файл, чтобы начать.'),
    'download': ('📥 Send result again', '📥 Natijani qayta yuborish', '📥 Прислать результат снова'),
    'result_expired': ('⌛ This result is no longer stored. Send the original file to try again.', '⌛ Natijaning saqlash muddati tugagan. Asl faylni qayta yuboring.', '⌛ Срок хранения истёк. Отправьте исходный файл ещё раз.'),
    'retry_task': ('🔄 Review & retry', '🔄 Tekshirib qayta urinish', '🔄 Проверить и повторить'),
    'link_methods': ('🔑 Sign-in methods', '🔑 Kirish usullari', '🔑 Способы входа'),
    'linked_methods': ('Sign in with', 'Kirish usullari', 'Способы входа'),
    'link_instructions': ('Use email or Google already? Sign in to that account on the website → Settings → Sign-in methods → Connect Telegram. Approve here, then return to the same browser.', 'Email yoki Google bilan kirganmisiz? Saytda o‘sha hisobga kiring → Sozlamalar → Kirish usullari → Telegramni ulash. Bu yerda tasdiqlab, o‘sha brauzerga qayting.', 'Уже входите через email или Google? На сайте войдите в тот аккаунт → Настройки → Способы входа → Подключить Telegram. Подтвердите здесь и вернитесь в тот же браузер.'),
    'guide': ('📎 Send a file → choose what to do → Start.\n✨ Or tap PDF on a topic or Slides on a topic: describe what you want in one message, and check the cost before it runs.\n🔒 Enter PDF passwords and edit PDFs in the web app.', '📎 Fayl yuboring → amalni tanlang → Boshlash.\n✨ Yoki «Mavzuga oid PDF» yoki «Mavzuga oid Slayd»ni bosing: nima kerakligini bitta xabarda yozing va narxini tasdiqlang.\n🔒 PDF parollarini kiriting va PDF tahrirlashni veb ilovada bajaring.', '📎 Отправьте файл → выберите действие → Начать.\n✨ Или нажмите «PDF по теме» или «Слайды по теме»: опишите задачу одним сообщением и подтвердите стоимость.\n🔒 Пароли PDF вводите и редактируйте PDF на сайте.'),
    # Contacts & support: the two Telegram accounts set in the admin.
    'contacts_button': ('📞 Contacts & support', '📞 Aloqa va yordam', '📞 Контакты и поддержка'),
    'contacts_title': ('📞 Contacts & support', '📞 Aloqa va yordam', '📞 Контакты и поддержка'),
    'contacts_support': ('💬 Support', '💬 Yordam', '💬 Поддержка'),
    'contacts_ads': ('📣 Advertising and partnerships', '📣 Reklama va hamkorlik', '📣 Реклама и сотрудничество'),
    'contacts_write_support': ('💬 Write to support', '💬 Yordamga yozish', '💬 Написать в поддержку'),
    'contacts_write_ads': ('📣 Write about advertising', '📣 Reklama bo‘yicha yozish', '📣 Написать о рекламе'),
    'contacts_none': ('Contacts will appear here soon.', 'Aloqa ma’lumotlari tez orada shu yerda bo‘ladi.', 'Контакты скоро появятся здесь.'),
    'how_it_works': ('💡 How it works', '💡 Qanday ishlaydi', '💡 Как это работает'),
    'fallback': ('📎 Send a file or use the buttons below.', '📎 Fayl yuboring yoki quyidagi tugmalardan foydalaning.', '📎 Отправьте файл или выберите кнопку ниже.'),
    'unsupported': ('📎 Please send a PDF, JPG, PNG, Word (.docx) or PowerPoint (.pptx) file.', '📎 PDF, JPG, PNG, Word (.docx) yoki PowerPoint (.pptx) fayli yuboring.', '📎 Отправьте PDF, JPG, PNG, Word (.docx) или PowerPoint (.pptx).'),
    'resend': ('✅ Language saved. Send your file again to begin.', '✅ Til saqlandi. Boshlash uchun faylni qayta yuboring.', '✅ Язык сохранён. Отправьте файл ещё раз, чтобы начать.'),
    'web_tools': ('🌐 More tools on the web', '🌐 Saytda ko‘proq vositalar', '🌐 Больше инструментов на сайте'),
    'web_hint': ('🌐 Open the web app with the same account to edit PDFs and enter passwords securely.', '🌐 PDF tahrirlash va parollarni xavfsiz kiritish uchun shu hisob bilan veb ilovani oching.', '🌐 Откройте сайт с тем же аккаунтом, чтобы редактировать PDF и безопасно вводить пароли.'),
    'upload_more': ('📎 Add files', '📎 Fayl qo‘shish', '📎 Добавить файлы'),
    'one_file_hint': ('📎 This tool takes one file. Remove the extras or start a new task.', '📎 Bu vositaga bitta fayl kerak. Ortiqchasini olib tashlang yoki yangi vazifa boshlang.', '📎 Нужен один файл. Уберите лишние или начните новую задачу.'),
    'photo_hint': ('📷 Photo added. Next time, send as a file to keep the original quality.', '📷 Rasm qo‘shildi. Asl sifatni saqlash uchun keyingi safar fayl sifatida yuboring.', '📷 Фото добавлено. Для исходного качества отправляйте изображение как файл.'),
    'prompt_invalid': ('Try the format in the example, or tap Back.', 'Namunadagi shaklda yozing yoki Orqaga bosing.', 'Попробуйте ввести как в примере или нажмите «Назад».'),
    'free_plan': ('Free', 'Bepul', 'Бесплатный'),
    'resets': ('Resets', 'Yangilanadi', 'Обновится'),
    'plan_label': ('Plan', 'Tarif', 'Тариф'),
    'plans': ('⭐ Plans & packs', '⭐ Tariflar va paketlar', '⭐ Тарифы и пакеты'),
    'usage_button': ('📊 My allowance', '📊 Limitlarim', '📊 Мои лимиты'),
    'subscription': ('💳 Subscription', '💳 Obuna', '💳 Подписка'),
    # The home screen's way to the plans: an invitation, not a status page.
    'subscribe_button': ('💎 Subscribe', '💎 Obuna bo‘lish', '💎 Оформить подписку'),
    'quota_hint': ('Your allowance isn’t enough for this task. Use fewer files or pages, or choose a plan.', 'Bu vazifaga limit yetmaydi. Kamroq fayl yoki sahifa tanlang, yoxud tarifni yangilang.', 'Лимита не хватает. Выберите меньше файлов или страниц либо другой тариф.'),
    'limits': ('📎 Bot limit: 20 MB per file. Use the website for larger files.', '📎 Botda: har fayl 20 MB gacha. Kattaroq fayl uchun saytdan foydalaning.', '📎 В боте: до 20 МБ на файл. Для больших файлов используйте сайт.'),
    'retention': ('🕒 Server files are stored for 24 hours. Copies sent here stay in your chat.', '🕒 Server fayllari 24 soat saqlanadi. Bu yerga yuborilgan nusxalar chatda qoladi.', '🕒 Файлы на сервере хранятся 24 часа. Отправленные сюда копии остаются в чате.'),
    # AI generation. The studio's own errors are translated in errors.py.
    'ai_ask_topic': ('✍️ Describe what you want. Say everything in one message: the subject, who it is for, the tone, and how many pages.', '✍️ Nima kerakligini yozing. Hammasini bitta xabarda ayting: mavzu, kim uchun, uslub va necha sahifa.', '✍️ Опишите, что нужно. Всё одним сообщением: тема, для кого, тон и сколько страниц.'),
    'ai_pages_hint': ('No page count in your message means 5. For slides you can also ask for a look: “dark”, “bold”, or a colour.', 'Xabarda sahifa soni bo‘lmasa, 5 ta bo‘ladi. Slaydlar uchun ko‘rinishni ham so‘rashingiz mumkin: «qorong‘i», «yorqin» yoki rang.', 'Если число страниц не указано, будет 5. Для слайдов можно попросить и вид: «тёмная», «ярко» или цвет.'),
    'ai_examples': ('💡 Example descriptions', '💡 Namuna tavsiflar', '💡 Примеры описаний'),
    'ai_examples_title': ('💡 Write it like this', '💡 Mana shunday yozing', '💡 Пишите вот так'),
    'ai_pages': ('Pages', 'Sahifalar', 'Страниц'),
    'ai_pages_clamped': ('{asked} asked for; {given} is the most your plan allows.', '{asked} so‘raldi; tarifingiz {given} tagacha ruxsat beradi.', 'Запрошено {asked}; тариф допускает {given}.'),
    'ai_topic_empty': ('✍️ I need a description before I can start.', '✍️ Boshlashim uchun tavsif kerak.', '✍️ Чтобы начать, нужно описание.'),
    'ai_preparing': ('⏳ Preparing your draft…', '⏳ Qoralama tayyorlanmoqda…', '⏳ Готовлю черновик…'),
    'ai_generate': ('✨ Generate', '✨ Yaratish', '✨ Создать'),
    'ai_change_topic': ('✏️ Change the description', '✏️ Tavsifni o‘zgartirish', '✏️ Изменить описание'),
    'ai_review_hint': ('Nothing is charged until you tap Generate.', '«Yaratish» tugmasini bosmaguningizcha hech narsa hisoblanmaydi.', 'Ничего не списывается, пока вы не нажмёте «Создать».'),
    'ai_back': ('◀️ Back', '◀️ Orqaga', '◀️ Назад'),
    'ai_revise': ('✏️ Make changes', '✏️ O‘zgartirish kiritish', '✏️ Внести изменения'),
    'ai_revise_title': ('✏️ What should change?', '✏️ Nimani o‘zgartiramiz?', '✏️ Что изменить?'),
    'ai_revise_ask': ('Describe the change in one message. Everything you do not mention stays exactly as it is.', 'O‘zgarishni bitta xabarda yozing. Siz aytmagan hamma narsa o‘z holicha qoladi.', 'Опишите изменение одним сообщением. Всё, о чём вы не упомянете, останется как есть.'),
    'ai_revise_examples': ('Make section 2 shorter · Use a friendlier tone · Add an example to each page · Same document in 8 pages', '2-bo‘limni qisqartiring · Do‘stona uslubda yozing · Har sahifaga misol qo‘shing · Xuddi shu hujjat 8 sahifada', 'Сократите раздел 2 · Сделайте тон дружелюбнее · Добавьте пример на каждую страницу · То же самое на 8 страницах'),
    'ai_revise_of': ('Changing', 'O‘zgartirilmoqda', 'Изменяем'),
    'ai_open_web': ('🌐 Open in web app', '🌐 Veb ilovada ochish', '🌐 Открыть в веб-приложении'),
    'ai_busy': ('⏳ One moment — still working on your last request.', '⏳ Bir lahza — oldingi so‘rovingiz ustida ishlanmoqda.', '⏳ Секунду — ещё обрабатываю прошлый запрос.'),
    # A finished document can carry a note about what was adjusted to match what
    # was asked for. These are keyed by the job's own warning codes.
    'questions_trimmed': ('ℹ️ Questions you did not ask for were left out, and not charged for.', 'ℹ️ So‘ramagan savollar qo‘shilmadi va hisoblanmadi.', 'ℹ️ Вопросы, которые вы не запрашивали, не добавлены и не оплачены.'),
    'sections_trimmed': ('ℹ️ The document was trimmed to the number of pages you asked for.', 'ℹ️ Hujjat siz so‘ragan sahifa soniga qisqartirildi.', 'ℹ️ Документ сокращён до запрошенного количества страниц.'),
    'images_skipped': ('ℹ️ A photo could not be added, so that slide was set as text. Nothing extra was charged.', 'ℹ️ Rasm qo‘shib bo‘lmadi, shuning uchun o‘sha slayd matn sifatida tayyorlandi. Qo‘shimcha to‘lov olinmadi.', 'ℹ️ Фото добавить не удалось, поэтому слайд оформлен текстом. Ничего дополнительно не списано.'),
    'images_limited': ('ℹ️ Your plan includes a set number of photos per deck; the other photo slides were set as text.', 'ℹ️ Tarifingizda bir taqdimot uchun rasmlar soni cheklangan; qolgan rasmli slaydlar matn sifatida tayyorlandi.', 'ℹ️ В вашем тарифе ограничено число фото на презентацию; остальные слайды с фото оформлены текстом.'),
    'citations_dropped': ('ℹ️ A source reference that did not match any file you sent was left out.', 'ℹ️ Siz yuborgan fayllarga mos kelmagan manba havolasi qo‘shilmadi.', 'ℹ️ Ссылка на источник, не совпавшая с вашими файлами, не добавлена.'),
    'shortened_to_fit': ('ℹ️ A section was longer than its page, so its end was trimmed to keep the page count you asked for.', 'ℹ️ Bir bo‘lim sahifasiga sig‘madi, shuning uchun siz so‘ragan sahifa soni saqlanib, oxiri qisqartirildi.', 'ℹ️ Один раздел не помещался на страницу, поэтому его конец сокращён, чтобы сохранить запрошенное число страниц.'),
    'longer_than_quoted': ('ℹ️ This came out a little longer than estimated. You were charged for the pages you asked for, not the extra.', 'ℹ️ Hujjat taxmindan biroz uzunroq chiqdi. Siz so‘ragan sahifalar uchun hisoblandi, qo‘shimchasi uchun emas.', 'ℹ️ Документ вышел чуть длиннее, чем ожидалось. Оплачены страницы, которые вы запросили, а не лишние.'),
}

# Keep the older keys for commands, saved controls and transport compatibility.
# They share the same tone as the primary flow instead of exposing command syntax.
LEGACY_MESSAGES = {
    'welcome': ('👋 Welcome to PDF Master! Send a file to begin. Server copies are kept for 24 hours.', '👋 PDF Master’ga xush kelibsiz! Boshlash uchun fayl yuboring. Serverdagi nusxalar 24 soat saqlanadi.', '👋 Добро пожаловать в PDF Master! Отправьте файл. Копии на сервере хранятся 24 часа.'),
    'tools': ('🧰 Choose what to do with your file.', '🧰 Fayl bilan nima qilishni tanlang.', '🧰 Выберите действие с файлом.'),
    'received': ('📎 File added. Send more or tap Start when ready.', '📎 Fayl qo‘shildi. Yana yuboring yoki Boshlashni bosing.', '📎 Файл добавлен. Отправьте ещё или нажмите «Начать».'),
    'done': ('✅ Check your files and usage, then tap Start.', '✅ Fayllar va sarfni tekshirib, Boshlashni bosing.', '✅ Проверьте файлы и расход лимита, затем нажмите «Начать».'),
    'run': ('▶️ Start', '▶️ Boshlash', '▶️ Начать'),
    'empty': ('📎 Send a file first.', '📎 Avval fayl yuboring.', '📎 Сначала отправьте файл.'),
    'working': ('⏳ Working on your file…', '⏳ Fayl tayyorlanmoqda…', '⏳ Обрабатываю файл…'),
    'result': ('✅ Your result is ready! Server copies expire after 24 hours; files sent here stay in the chat.', '✅ Natija tayyor! Serverdagi nusxalar 24 soatdan keyin o‘chiriladi; bu yerdagi fayllar chatda qoladi.', '✅ Готово! Копии на сервере удалятся через 24 часа; присланные файлы останутся в чате.'),
    'no_op': ('✅ Your file is unchanged. No allowance was used.', '✅ Fayl o‘zgarmadi. Limit sarflanmadi.', '✅ Файл не изменился. Лимит не списан.'),
    'support': ('💬 Tell us what you need help with.', '💬 Qanday yordam kerakligini yozing.', '💬 Напишите, с чем нужна помощь.'),
    'ticket': ('✅ Your message is with support.', '✅ Xabaringiz yordam xizmatiga yuborildi.', '✅ Сообщение передано в поддержку.'),
    'cancel': ('✅ Draft discarded. Your files and task history are saved.', '✅ Qoralama bekor qilindi. Fayllar va vazifalar tarixi saqlandi.', '✅ Черновик удалён. Файлы и история задач сохранены.'),
    'help': ('📎 Send a file → choose an action → Start. Use the buttons to adjust options or find recent results.', '📎 Fayl yuboring → amalni tanlang → Boshlash. Sozlamalar va natijalar uchun tugmalardan foydalaning.', '📎 Отправьте файл → выберите действие → Начать. Настройки и результаты доступны по кнопкам.'),
    'login': ('🔐 Approve sign-in only if you requested it in this browser:', '🔐 Faqat ushbu brauzerda kirishni o‘zingiz boshlagan bo‘lsangiz, tasdiqlang:', '🔐 Подтверждайте вход, только если вы запросили его в этом браузере:'),
    'confirm': ('🔐 Approve sign-in', '🔐 Kirishni tasdiqlash', '🔐 Подтвердить вход'),
    'approved': ('✅ Sign-in approved. Return to the same browser.', '✅ Kirish tasdiqlandi. O‘sha brauzerga qayting.', '✅ Вход подтверждён. Вернитесь в тот же браузер.'),
    'language': ('🌐 Choose your language.', '🌐 Tilni tanlang.', '🌐 Выберите язык.'),
    'open': ('🌐 Open web app', '🌐 Veb ilova', '🌐 Открыть сайт'),
    'terms': ('🕒 Server files expire after 24 hours; copies sent to Telegram stay in your chat.\n✨ For AI documents we keep your description and the result for 30 days so our team can check quality and stop misuse; then they are deleted.\n⭐ Purchases activate after payment is confirmed. Test mode spends no real Stars.\nPayment help: /paysupport', '🕒 Server fayllari 24 soatdan keyin o‘chiriladi; Telegram’ga yuborilgan nusxalar chatda qoladi.\n✨ AI hujjatlar uchun tavsifingiz va natija 30 kun saqlanadi — jamoamiz sifatni tekshirishi va suiiste’molning oldini olishi uchun; keyin o‘chiriladi.\n⭐ Xarid to‘lov tasdiqlangach faollashadi. Sinovda haqiqiy Stars sarflanmaydi.\nTo‘lov yordami: /paysupport', '🕒 Файлы сервера удаляются через 24 часа; копии в Telegram остаются в чате.\n✨ Для AI-документов мы храним ваше описание и результат 30 дней, чтобы команда могла проверять качество и предотвращать злоупотребления; затем они удаляются.\n⭐ Покупки активируются после подтверждения оплаты. В тестовом режиме настоящие Stars не тратятся.\nПомощь с оплатой: /paysupport'),
    'settings': ('⚙️ Task options', '⚙️ Vazifa sozlamalari', '⚙️ Настройки задачи'),
    'done_button': ('✅ Review & start', '✅ Tekshirish va boshlash', '✅ Проверить и начать'),
    'back': ('← Back', '← Orqaga', '← Назад'),
    'next': ('🧰 More tools', '🧰 Boshqa vositalar', '🧰 Ещё инструменты'),
    'pages_hint': ('📑 Choose pages, for example: 1,3-5.', '📑 Sahifalarni tanlang, masalan: 1,3-5.', '📑 Выберите страницы, например: 1,3-5.'),
    'split_hint': ('✂️ Choose page groups, or save each page separately.', '✂️ Sahifa guruhlarini tanlang yoki har sahifani alohida saqlang.', '✂️ Выберите группы страниц или сохраните каждую отдельно.'),
    'reorder_hint': ('↕️ Set the order of all pages, for example: 3,1,2.', '↕️ Barcha sahifalar tartibini yozing, masalan: 3,1,2.', '↕️ Задайте порядок всех страниц, например: 3,1,2.'),
    'merge_hint': ('↕️ Files merge in the order shown. You can change it below.', '↕️ Fayllar shu tartibda birlashadi. Quyida o‘zgartirishingiz mumkin.', '↕️ Файлы объединятся в указанном порядке. Его можно изменить ниже.'),
    'image_hint': ('⚙️ Adjust the paper, orientation or margins if needed.', '⚙️ Kerak bo‘lsa qog‘oz, yo‘nalish yoki hoshiyani sozlang.', '⚙️ При желании настройте бумагу, ориентацию и поля.'),
    'secure': ('🔒 Enter PDF passwords only in the web app. Please don’t send them here.', '🔒 PDF parollarini faqat veb ilovada kiriting. Bu chatga yubormang.', '🔒 Вводите пароли PDF только на сайте. Не отправляйте их сюда.'),
    'rotate_label': ('Rotation', 'Aylantirish', 'Поворот'),
    'format_label': ('Image format', 'Rasm formati', 'Формат изображения'),
    'paper_label': ('Paper size', 'Qog‘oz o‘lchami', 'Размер бумаги'),
    'portrait': ('↕️ Portrait', '↕️ Tik', '↕️ Книжная'),
    'landscape': ('↔️ Landscape', '↔️ Yotiq', '↔️ Альбомная'),
    'auto': ('✨ Auto', '✨ Avtomatik', '✨ Авто'),
    'quote_cost': ('Tasks / page units', 'Vazifa / sahifa birligi', 'Задачи / единицы страниц'),
    'balance': ('Available tasks / page units', 'Mavjud vazifa / sahifa birligi', 'Доступно задач / единиц страниц'),
    'expires': ('Valid until (UTC)', 'Amal qiladi (UTC)', 'Действует до (UTC)'),
    'parameters': ('Options', 'Sozlamalar', 'Настройки'),
    'add': ('📎 Add to this task', '📎 Shu vazifaga qo‘shish', '📎 Добавить к задаче'),
    'new': ('➕ New task', '➕ Yangi vazifa', '➕ Новая задача'),
    'new_file': ('📎 Add this file to your draft, or start fresh?', '📎 Faylni qoralamaga qo‘shamizmi yoki yangidan boshlaymizmi?', '📎 Добавить файл к черновику или начать заново?'),
    'controls_expired': ('That button is from an earlier step. Continue your task or open the menu.', 'Bu tugma oldingi bosqichdan qolgan. Vazifani davom ettiring yoki menyuni oching.', 'Эта кнопка из прошлого шага. Продолжите задачу или откройте меню.'),
    'stale_button': ('That button was from an earlier step, so here is the menu.', 'Bu tugma oldingi bosqichdan qolgan edi, mana menyu.', 'Эта кнопка была из прошлого шага, поэтому вот меню.'),
    'stale_reply': ('It has been a while since that question, so let’s start from the menu.', 'O‘sha savoldan beri ancha vaqt o‘tdi, keling, menyudan boshlaymiz.', 'С того вопроса прошло время, давайте начнём с меню.'),
    'no_preview': ('A preview isn’t available. You can still process the file.', 'Ko‘rib chiqish imkoni yo‘q. Fayl bilan ishlashni davom ettirishingiz mumkin.', 'Предпросмотр недоступен. Файл всё равно можно обработать.'),
    'preview': ('👁 Preview page 1', '👁 1-sahifani ko‘rish', '👁 Посмотреть страницу 1'),
    'link_login': ('🔗 Connect Telegram to your existing PDF Master account? Approve only if you started this in account settings:', '🔗 Telegramni mavjud PDF Master hisobingizga ulaymizmi? Faqat hisob sozlamalarida o‘zingiz boshlagan bo‘lsangiz, tasdiqlang:', '🔗 Подключить Telegram к вашему аккаунту PDF Master? Подтверждайте, только если вы начали это в настройках аккаунта:'),
    'link_confirm': ('🔗 Connect Telegram', '🔗 Telegramni ulash', '🔗 Подключить Telegram'),
    'link_approved': ('✅ Telegram approved. Return to the same browser to finish linking.', '✅ Telegram tasdiqlandi. Ulashni tugatish uchun o‘sha brauzerga qayting.', '✅ Telegram подтверждён. Вернитесь в тот же браузер, чтобы завершить привязку.'),
}

PROMPT_EXAMPLES = {
    'ai.pdf_topic': (
        ('I need a 10 page university assignment on the history of trade routes through Bukhara. Academic tone, each section under a clear heading.',
         'Universitetga mustaqil ish kerak: Buxoro savdo yo‘llari tarixi, 10 sahifa. Ilmiy uslubda yozing, har bo‘lim aniq sarlavha ostida bo‘lsin.',
         'Нужна самостоятельная работа для университета: история торговых путей Бухары, 10 страниц. Академическим стилем, каждый раздел под ясным заголовком.'),
        ('A 3 page guide for the new waiters at my cafe: greeting a guest, taking an order, what to do about a complaint. Friendly but clear.',
         'Kafemdagi yangi ofitsiantlar uchun 3 sahifalik qo‘llanma yozib bering: mijozni kutib olish, buyurtma olish, shikoyat bo‘lsa nima qilish. Do‘stona, lekin aniq.',
         'Напишите инструкцию на 3 страницы для новых официантов в моём кафе: встретить гостя, принять заказ, что делать при жалобе. Дружелюбно, но ясно.'),
        ('A 4 page handout for my year 7 biology lesson on cell structure. Keep it plain, one example on every page, 5 quiz questions at the end.',
         '7-sinf biologiya darsiga 4 sahifalik tarqatma tayyorlab bering — hujayra tuzilishi haqida. Sodda tilda bo‘lsin, har sahifada bitta misol, oxirida 5 ta test savoli.',
         'Сделайте раздатку на 4 страницы для урока биологии в 7 классе — о строении клетки. Простым языком, на каждой странице пример, в конце 5 тестовых вопросов.'),
    ),
    'ai.pptx': (
        ('10 slides for an open lesson — year 9 geography, the shrinking of the Aral Sea. One idea per slide, 5 questions at the end. Make it look good, in navy.',
         'Ochiq darsga 10 ta slayd kerak — 9-sinf geografiya, Orol dengizi muammosi. Har slaydda bitta fikr, oxirida 5 ta savol. Ko‘k rangda chiroyli chiqsin.',
         'Нужно 10 слайдов для открытого урока — география, 9 класс, проблема Аральского моря. Одна мысль на слайд, 5 вопросов в конце. В синем, чтобы выглядело красиво.'),
        ('6 slides pitching my online shop to investors: the problem, the solution, the market, the numbers, the ask. Confident, no jargon.',
         'Investorlarga online do‘konim haqida 6 ta slayd: muammo, yechim, bozor, raqamlar, nima so‘rayotganim. Ishonchli ohangda, jargonsiz.',
         '6 слайдов о моём интернет-магазине для инвесторов: проблема, решение, рынок, цифры, запрос. Уверенно, без жаргона.'),
        ('7 slides for the monthly meeting: the sales figures, what went well, what slipped, the plan for next month. Show the sales as a chart.',
         'Oylik yig‘ilishga 7 ta slayd: sotuv raqamlari, nima yaxshi ketdi, nima oqsadi, keyingi oy rejasi. Sotuvni diagramma qilib ko‘rsating.',
         '7 слайдов для месячного собрания: цифры продаж, что получилось, что нет, план на следующий месяц. Продажи покажите диаграммой.'),
    ),
}

TOOL_LABELS = {
    'pdf.merge': ('📑 Merge PDFs', '📑 PDF birlashtirish', '📑 Объединить PDF'),
    'pdf.compress': ('🗜 Compress PDF', '🗜 PDF hajmini kamaytirish', '🗜 Сжать PDF'),
    'pdf.split': ('✂️ Split PDF', '✂️ PDF bo‘lish', '✂️ Разделить PDF'),
    'pdf.extract_pages': ('📑 Extract pages', '📑 Sahifalarni ajratish', '📑 Извлечь страницы'),
    'pdf.delete_pages': ('🗑 Delete pages', '🗑 Sahifalarni o‘chirish', '🗑 Удалить страницы'),
    'pdf.reorder': ('↕️ Reorder pages', '↕️ Sahifalar tartibi', '↕️ Порядок страниц'),
    'pdf.rotate': ('🔄 Rotate pages', '🔄 Sahifalarni aylantirish', '🔄 Повернуть страницы'),
    'pdf.images_to_pdf': ('🖼 PDF from images', '🖼 Rasmlardan PDF', '🖼 PDF из фото'),
    'pdf.to_images': ('🖼 PDF → images', '🖼 PDF → rasmlar', '🖼 PDF → изображения'),
    'convert.word_to_pdf': ('📝 Word → PDF', '📝 Word → PDF', '📝 Word → PDF'),
    'convert.pptx_to_pdf': ('📊 PowerPoint → PDF', '📊 PowerPoint → PDF', '📊 PowerPoint → PDF'),
    # The two AI services. Names are kept in step with the web app's locales.
    'ai.pdf_topic': ('✨ PDF on a topic · AI', '✨ Mavzuga oid PDF · AI', '✨ PDF по теме · ИИ'),
    'ai.pptx': ('✨ Slides on a topic · AI', '✨ Mavzuga oid Slayd · AI', '✨ Слайды по теме · ИИ'),
}

UX = {locale: {key: values[index] for key, values in MESSAGES.items()} for index, locale in enumerate(LOCALES)}
LEGACY_COPY = {locale: {key: values[index] for key, values in LEGACY_MESSAGES.items()} for index, locale in enumerate(LOCALES)}
TOOL_NAMES = {key: dict(zip(LOCALES, labels)) for key, labels in TOOL_LABELS.items()}
STATUS = {
    'en': {'queued': '⏳ Queued', 'running': '⚙️ Processing', 'finalizing': '📦 Finishing', 'succeeded': '✅ Ready', 'failed': '⚠️ Couldn’t finish', 'canceled': '✖️ Cancelled', 'expired': '⌛ Expired', 'no_op': '✅ No change'},
    'uz': {'queued': '⏳ Navbatda', 'running': '⚙️ Tayyorlanmoqda', 'finalizing': '📦 Yakunlanmoqda', 'succeeded': '✅ Tayyor', 'failed': '⚠️ Bajarilmadi', 'canceled': '✖️ Bekor qilindi', 'expired': '⌛ Muddati tugagan', 'no_op': '✅ O‘zgarish yo‘q'},
    'ru': {'queued': '⏳ В очереди', 'running': '⚙️ Обработка', 'finalizing': '📦 Завершение', 'succeeded': '✅ Готово', 'failed': '⚠️ Не удалось завершить', 'canceled': '✖️ Отменено', 'expired': '⌛ Срок истёк', 'no_op': '✅ Без изменений'},
}
