"""Short, parallel EN/UZ/RU copy for the button-led Telegram experience."""
MESSAGES = {
'download_error': ('The upload could not be downloaded. Please attach the file again.', 'Faylni yuklab bo‘lmadi. Iltimos, qayta yuboring.', 'Не удалось скачать файл. Прикрепите его ещё раз.'),
'wrong_file': ('This file does not match the chosen tool. Your task is unchanged; send the file type shown below or choose another tool.', 'Fayl tanlangan vositaga mos emas. Vazifa o‘zgarmadi; quyida ko‘rsatilgan turdagi faylni yuboring yoki boshqa vosita tanlang.', 'Файл не подходит выбранному инструменту. Задача не изменена; отправьте файл указанного ниже типа или выберите другой инструмент.'),
'home_title': ('Your documents, made simple.', 'Hujjatlar bilan ishlash oson.', 'Работать с документами — просто.'),
'home_body': ('Choose an action below, or send a document to begin. Your files, plan and allowance are shared with the web app.', 'Quyidan amal tanlang yoki boshlash uchun hujjat yuboring. Fayllar, tarif va limitlar veb ilova bilan umumiy.', 'Выберите действие или отправьте документ. Файлы, тариф и лимиты общие с веб-приложением.'),
'home': ('Main menu', 'Bosh menyu', 'Главное меню'),
'pdf_tools': ('PDF tools', 'PDF vositalari', 'Инструменты PDF'),
'convert_tools': ('Convert files', 'Faylni o‘girish', 'Конвертация'),
'recent': ('Recent tasks', 'So‘nggi vazifalar', 'Последние задачи'),
'account': ('My account', 'Mening hisobim', 'Мой аккаунт'),
'help_button': ('Help & support', 'Yordam', 'Помощь'),
'language_button': ('Change language', 'Tilni o‘zgartirish', 'Изменить язык'),
'continue_task': ('Continue current task', 'Vazifani davom ettirish', 'Продолжить задачу'),
'choose_tool': ('1 · Choose a tool\nWhat would you like to do?', '1 · Vosita tanlang\nNima qilmoqchisiz?', '1 · Выберите инструмент\nЧто нужно сделать?'),
'upload_title': ('2 · Add your files', '2 · Fayllarni yuboring', '2 · Добавьте файлы'),
'upload_pdf': ('Send a PDF as a document using the attachment button. Maximum 20 MB per file in the bot.', 'Biriktirish tugmasi orqali PDF hujjat yuboring. Botda har bir fayl 20 MB gacha.', 'Прикрепите PDF как документ. В боте принимаются файлы до 20 МБ.'),
'upload_merge': ('Send at least two PDFs, in the order you want to merge them. You can change the order below.', 'Kamida ikkita PDF’ni birlashtirish tartibida yuboring. Tartibni keyin o‘zgartirishingiz mumkin.', 'Отправьте минимум два PDF в нужном порядке. Порядок можно изменить ниже.'),
'upload_images': ('Send JPG or PNG images. Attach them as files to keep their original quality.', 'JPG yoki PNG rasmlar yuboring. Sifatni saqlash uchun fayl sifatida biriktiring.', 'Отправьте JPG или PNG. Прикрепляйте как файлы, чтобы сохранить качество.'),
'upload_word': ('Send one Word document (.docx).', 'Bitta Word hujjati (.docx) yuboring.', 'Отправьте один документ Word (.docx).'),
'upload_slides': ('Send one PowerPoint presentation (.pptx).', 'Bitta PowerPoint taqdimoti (.pptx) yuboring.', 'Отправьте одну презентацию PowerPoint (.pptx).'),
'upload_received': ('Files received: {count}. Send more files or review the task below.', '{count} ta fayl qabul qilindi. Yana yuboring yoki vazifani quyida tekshiring.', 'Получено файлов: {count}. Добавьте ещё или проверьте задачу ниже.'),
'options_title': ('3 · Check your files and settings', '3 · Fayllar va sozlamalarni tekshiring', '3 · Проверьте файлы и настройки'),
'files': ('Files', 'Fayllar', 'Файлы'),
'pages': ('Pages', 'Sahifalar', 'Страницы'),
'options_default': ('Default settings', 'Standart sozlamalar', 'Стандартные настройки'),
'page_selection': ('Choose pages', 'Sahifalarni tanlash', 'Выбрать страницы'),
'page_order': ('Set page order', 'Sahifalar tartibi', 'Порядок страниц'),
'split_groups': ('Choose page groups', 'Sahifa guruhlari', 'Группы страниц'),
'all_pages': ('All pages', 'Barcha sahifalar', 'Все страницы'),
'each_page': ('One file per page', 'Har sahifa alohida', 'Каждая страница отдельно'),
'file_order': ('Change file order', 'Fayllar tartibi', 'Порядок файлов'),
'remove_file': ('Remove a file', 'Faylni olib tashlash', 'Убрать файл'),
'margin_button': ('Set margins', 'Hoshiyani sozlash', 'Настроить поля'),
'pages_prompt': ('Which pages? Send numbers or ranges, for example: 1,3-5. Choose Back to keep your current settings.', 'Qaysi sahifalar? Masalan, 1,3-5 yuboring. Joriy sozlamani saqlash uchun Orqaga bosing.', 'Какие страницы? Введите номера или диапазоны: 1,3-5. Кнопка «Назад» сохранит текущие настройки.'),
'reorder_prompt': ('Send every page number once, in the new order. Example: 3,1,2.', 'Har bir sahifa raqamini yangi tartibda bir marta yozing. Masalan: 3,1,2.', 'Укажите все страницы по одному разу в новом порядке. Например: 3,1,2.'),
'split_prompt': ('Send page groups separated by a semicolon. Example: 1-2;3-5.', 'Sahifa guruhlarini nuqtali vergul bilan ajrating. Masalan: 1-2;3-5.', 'Разделите группы страниц точкой с запятой. Например: 1-2;3-5.'),
'order_prompt': ('Send all file numbers in the new order. Example: 2,1. Your documents are listed above.', 'Barcha fayl raqamlarini yangi tartibda yozing. Masalan: 2,1. Fayllar yuqorida ko‘rsatilgan.', 'Введите все номера файлов в новом порядке. Например: 2,1. Список файлов показан выше.'),
'remove_prompt': ('Send the number of the file to remove. Example: 2. This only removes it from this task.', 'Olib tashlanadigan fayl raqamini yuboring. Masalan: 2. Fayl faqat shu vazifadan olinadi.', 'Введите номер файла, который нужно убрать. Например: 2. Он будет убран только из этой задачи.'),
'margin_prompt': ('Send the margin in points, from 0 to 72. Example: 24.', 'Hoshiyani 0–72 punkt oralig‘ida yozing. Masalan: 24.', 'Введите размер поля от 0 до 72 пунктов. Например: 24.'),
'review_title': ('4 · Ready to process?', '4 · Bajarishga tayyormi?', '4 · Всё готово?'),
'review_hint': ('Check the files, settings and allowance below. Processing starts only when you confirm.', 'Fayllar, sozlamalar va sarfni tekshiring. Jarayon faqat tasdiqlaganingizdan keyin boshlanadi.', 'Проверьте файлы, настройки и расход лимита. Обработка начнётся после подтверждения.'),
'cost': ('This task uses', 'Vazifa sarfi', 'Будет использовано'),
'available': ('Available', 'Mavjud', 'Доступно'),
'file_tasks': ('file tasks', 'fayl vazifasi', 'задач'),
'page_units': ('page units', 'sahifa birligi', 'единиц страниц'),
'ai_credits': ('AI credits', 'AI kredit', 'кредитов ИИ'),
'edit_settings': ('Back to settings', 'Sozlamalarga qaytish', 'К настройкам'),
'cancel_button': ('Cancel task', 'Vazifani bekor qilish', 'Отменить задачу'),
'cancel_question': ('Cancel this draft? Submitted tasks and saved files will stay in your account.', 'Joriy qoralama bekor qilinsinmi? Yuborilgan vazifalar va saqlangan fayllar hisobda qoladi.', 'Отменить черновик? Отправленные задачи и сохранённые файлы останутся в аккаунте.'),
'cancel_confirm': ('Yes, cancel draft', 'Ha, bekor qilish', 'Да, отменить черновик'),
'keep_task': ('Keep working', 'Davom etish', 'Продолжить работу'),
'new_question': ('Start a new task? This clears the current draft, but keeps your saved files and task history.', 'Yangi vazifa boshlansinmi? Joriy qoralama tozalanadi, lekin fayllar va tarix saqlanadi.', 'Начать новую задачу? Текущий черновик будет очищен, файлы и история сохранятся.'),
'new_confirm': ('Start fresh', 'Yangidan boshlash', 'Начать заново'),
'new_task': ('New task', 'Yangi vazifa', 'Новая задача'),
'processing': ('Processing your document…\nYou can leave this chat. Your result will be sent here when ready.', 'Hujjat qayta ishlanmoqda…\nChatdan chiqishingiz mumkin. Tayyor natija shu yerga yuboriladi.', 'Обрабатываем документ…\nМожно закрыть чат. Готовый результат придёт сюда.'),
'check_status': ('Check status', 'Holatni tekshirish', 'Проверить статус'),
'queued': ('Your task is queued. We will send the result here when it is ready.', 'Vazifa navbatda. Natija tayyor bo‘lganda shu yerga yuboramiz.', 'Задача в очереди. Результат будет отправлен сюда, когда он будет готов.'),
'recent_empty': ('No tasks yet. Choose a tool to create your first document.', 'Hozircha vazifalar yo‘q. Birinchi hujjat uchun vosita tanlang.', 'Пока нет задач. Выберите инструмент для первого документа.'),
'download': ('Send result again', 'Natijani qayta yuborish', 'Отправить результат снова'),
'result_expired': ('This result has expired. Upload the original document to create it again.', 'Natija muddati tugagan. Qayta yaratish uchun asl hujjatni yuklang.', 'Срок хранения результата истёк. Загрузите исходный документ заново.'),
'retry_task': ('Review and try again', 'Tekshirib qayta urinish', 'Проверить и повторить'),
'link_methods': ('Manage sign-in methods', 'Kirish usullarini boshqarish', 'Способы входа'),
'linked_methods': ('Connected sign-in methods', 'Ulangan kirish usullari', 'Подключённые способы входа'),
'link_instructions': ('Already use email or Google? Open that account in the web app, go to Settings → Sign-in methods → Connect Telegram. Approve the request here, then return to the same browser to finish.', 'Email yoki Google hisobingiz bormi? Veb ilovada o‘sha hisobga kiring: Sozlamalar → Kirish usullari → Telegramni ulash. Bu yerda tasdiqlang va tugatish uchun o‘sha brauzerga qayting.', 'Уже есть аккаунт с email или Google? Войдите в него на сайте: Настройки → Способы входа → Подключить Telegram. Подтвердите здесь, затем вернитесь в тот же браузер.'),
'support_prompt': ('Send your question in one message (5–4000 characters). Do not include passwords, login codes or payment card details.', 'Savolingizni bitta xabarda yozing (5–4000 belgi). Parol, kirish kodi yoki bank karta ma’lumotlarini yubormang.', 'Напишите вопрос одним сообщением (5–4000 символов). Не отправляйте пароли, коды входа или данные карты.'),
'support_confirm': ('Send this support request?', 'Yordam so‘rovi yuborilsinmi?', 'Отправить обращение?'),
'support_send': ('Send request', 'So‘rovni yuborish', 'Отправить обращение'),
'support_edit': ('Edit message', 'Xabarni tahrirlash', 'Изменить сообщение'),
'support_saved': ('Support request received. Reference: {reference}. You can follow up in the web app.', 'Yordam so‘rovi qabul qilindi. Raqam: {reference}. Veb ilovada davom ettirishingiz mumkin.', 'Обращение принято. Номер: {reference}. Продолжить переписку можно в веб-приложении.'),
'support_button': ('Contact support', 'Yordamga yozish', 'Написать в поддержку'),
'payment_help': ('Payment help', 'To‘lov bo‘yicha yordam', 'Помощь с оплатой'),
'guide': ('Choose a tool → add files → check settings → review → confirm. Use the buttons at each step. You can return to the main menu without losing your draft. PDF passwords belong only in the secure web workspace.', 'Vosita tanlang → fayl yuboring → sozlang → tekshiring → tasdiqlang. Har bosqichdagi tugmalardan foydalaning. Bosh menyuga qaytsangiz, qoralama saqlanadi. PDF parollarini faqat xavfsiz veb ilovada kiriting.', 'Выберите инструмент → добавьте файлы → настройте → проверьте → подтвердите. Используйте кнопки на каждом шаге. Главное меню не удаляет черновик. Пароли PDF вводите только в защищённом веб-приложении.'),
'fallback': ('Choose an action below. If you want to process a document, send it with the attachment button.', 'Quyidan amal tanlang. Hujjatni qayta ishlash uchun biriktirish tugmasi orqali yuboring.', 'Выберите действие ниже. Для обработки документа прикрепите его к сообщению.'),
'unsupported': ('I can work with PDF, JPG, PNG, Word and PowerPoint files. Please send one of these as a document.', 'PDF, JPG, PNG, Word va PowerPoint fayllari bilan ishlayman. Shulardan birini hujjat sifatida yuboring.', 'Я работаю с PDF, JPG, PNG, Word и PowerPoint. Отправьте один из этих файлов как документ.'),
'resend': ('Your language is saved. Please send your document again to begin.', 'Til saqlandi. Boshlash uchun hujjatingizni qayta yuboring.', 'Язык сохранён. Отправьте документ ещё раз, чтобы начать.'),
'web_tools': ('More tools in the web app', 'Veb ilovada boshqa vositalar', 'Больше инструментов на сайте'),
'web_hint': ('The web workspace includes document creation, study tools, editing and secure password entry. It uses this same account.', 'Veb ilovada hujjat yaratish, o‘rganish, tahrirlash va xavfsiz parol kiritish mavjud. Hisobingiz umumiy.', 'В веб-приложении доступны создание документов, учебные инструменты, редактор и безопасный ввод паролей. Аккаунт общий.'),
'upload_more': ('Add more files', 'Yana fayl qo‘shish', 'Добавить файлы'),
'one_file_hint': ('This tool works with one file. Remove extra files or start a new task.', 'Bu vosita bitta fayl bilan ishlaydi. Ortiqcha faylni olib tashlang yoki yangi vazifa boshlang.', 'Для этого инструмента нужен один файл. Уберите лишние файлы или начните новую задачу.'),
'photo_hint': ('Photo received. For the best quality, attach the original image as a file.', 'Rasm qabul qilindi. Eng yaxshi sifat uchun asl rasmni fayl sifatida yuboring.', 'Фото получено. Для лучшего качества прикрепите оригинал как файл.'),
'prompt_invalid': ('That input does not match the example. Please try again, or use Back.', 'Kiritilgan qiymat namunaga mos emas. Qayta urinib ko‘ring yoki Orqaga bosing.', 'Ввод не соответствует примеру. Попробуйте ещё раз или нажмите «Назад».'),
'plan_label': ('Plan', 'Tarif', 'Тариф'),
'plans': ('Plans & upgrades', 'Tariflar va paketlar', 'Тарифы и пакеты'),
'usage_button': ('My allowance', 'Mening limitim', 'Мои лимиты'),
'subscription': ('Subscription', 'Obuna', 'Подписка'),
'quota_hint': ('There is not enough allowance for this task. Choose a plan or reduce the selected files/pages.', 'Bu vazifa uchun limit yetarli emas. Tarif tanlang yoki fayl/sahifalar sonini kamaytiring.', 'Для задачи недостаточно лимита. Выберите тариф или уменьшите число файлов и страниц.'),
}
UX = {locale: {key: values[index] for key, values in MESSAGES.items()} for index, locale in enumerate(('en','uz','ru'))}
STATUS = {
'en': {'queued':'Queued','running':'Processing','finalizing':'Finishing','succeeded':'Ready','failed':'Could not finish','canceled':'Cancelled','expired':'Expired','no_op':'No change needed'},
'uz': {'queued':'Navbatda','running':'Bajarilmoqda','finalizing':'Yakunlanmoqda','succeeded':'Tayyor','failed':'Bajarilmadi','canceled':'Bekor qilindi','expired':'Muddati tugagan','no_op':'O‘zgarish kerak emas'},
'ru': {'queued':'В очереди','running':'Обработка','finalizing':'Завершение','succeeded':'Готово','failed':'Не удалось завершить','canceled':'Отменено','expired':'Срок истёк','no_op':'Изменений не требуется'},
}
